### ISSUE TITLE
All commands that rely on findProjectRoot fails

### ISSUE THREAD

**Issue by chronotc** [netlify/cli#145]
**- Do you want to request a *feature* or report a *bug*?**

Bug

**- What is the current behavior?**

Running any command apart from `netlify help` results in:

```
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type object
    at findProjectRoot (/usr/src/app/node_modules/netlify-cli/src/base/utils/projectRoot.js:15:30)
    at Object.<anonymous> (/usr/src/app/node_modules/netlify-cli/src/base/utils/projectRoot.js:19:14)
```

findProjectRoot makes the assumption that it will find one of these files: 
```
  const rootIndicators = [
    '.netlify',
    'netlify.toml',
    '.git'
  ]
```

**- If the current behavior is a bug, please provide the steps to reproduce.**

In a docker image without those files, run:

`netlify status`

**- What is the expected behavior?**

But when these files do not exist on the filesystem, the script should fallback to `cwd` as intended.

**- Please mention your node.js, and operating system version.**

netlify-cli/2.0.0 linux-x64 node-v10.6.0

**Comment by mabdullah353** [comment]
```
netlify deploy --prod  --dir="./build"
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type object
    at findProjectRoot (/usr/lib/node_modules/netlify-cli/src/base/utils/projectRoot.js:15:30)
    at Object.<anonymous> (/usr/lib/node_modules/netlify-cli/src/base/utils/projectRoot.js:19:14)
```

The above is failing for me, anyway to fix that? This happens when v2.0.0 is launched.

**Comment by bcomnes** [comment]
@mabdullah353 I think I see the issue.  Ill post back when its fixed.

**Comment by bcomnes** [comment]
I released a beta that should address this issue: see https://github.com/netlify/cli/pull/147#issuecomment-429497857

Expect a full release monday.

**Comment by mabdullah353** [comment]
@bcomnes Beta also not working:

```
[Container] 2018/10/15 05:40:31 Running command npm install netlify-cli@next -g
/usr/bin/ntl -> /usr/lib/node_modules/netlify-cli/bin/run
/usr/bin/netlify -> /usr/lib/node_modules/netlify-cli/bin/run
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/netlify-cli/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

+ netlify-cli@2.1.0-beta.1
added 1077 packages from 559 contributors in 14.934s



[Container] 2018/10/15 05:43:32 Running command netlify deploy --prod --dir="./build"
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type object
at findProjectRoot (/usr/lib/node_modules/netlify-cli/src/base/utils/project-root.js:16:30)
at Object.<anonymous> (/usr/lib/node_modules/netlify-cli/src/base/utils/project-root.js:20:14)

[Container] 2018/10/15 05:43:32 Command did not exit successfully netlify deploy --prod --dir="./build" exit status 1
[Container] 2018/10/15 05:43:32 Phase complete: POST_BUILD Success: false
```

**Comment by bcomnes** [comment]
Investigating this further.

**Comment by bcomnes** [comment]
I see the issue upon a closer reading.  Making a release.

**Comment by bcomnes** [comment]
🎉[`+ netlify-cli@2.1.1`](https://github.com/netlify/cli/releases/tag/v2.1.1)🎉

Give that a shot!
