### ISSUE TITLE
sites:list --json fails

### ISSUE THREAD

**Issue by mojodna** [netlify/cli#156]
**- Do you want to request a *feature* or report a *bug*?**

Bug.

**- What is the current behavior?**

```bash
$ node_modules/.bin/netlify sites:list --json
TypeError: Cannot convert undefined or null to object
    at sites.map.site (~/src/mojodna/stac-browser/node_modules/netlify-cli/src/commands/sites/list.js:33:23)
    at Array.map (<anonymous>)
    at SitesListCommand.run (~/src/mojodna/stac-browser/node_modules/netlify-cli/src/commands/sites/list.js:32:37)
```

`build_settings` is `null` for all of my sites in https://github.com/netlify/cli/blob/82c85f9adc5dd21464108822a85791c2a5832b58/src/commands/sites/list.js#L33

**- What is the expected behavior?**

`netlify sites:list --json` should output a JSON-formatted list of sites.

**- Please mention your node.js, and operating system version.**

MacOS 10.14 (Mojave)
Node.js v10.12.0

**Comment by bcomnes** [comment]
Thanks for the report, I'll take a look.
