### ISSUE TITLE
netlify deploy: "Error: Not Found"

### ISSUE THREAD

**Issue by arunsathiya** [netlify/cli#213]
I am having an issue similar to one previously reported: https://github.com/netlify/cli/issues/180

```
➜  drum-kit git:(master) ✗ DEBUG=* netlify deploy

  @oclif/config reading core plugin /usr/local/lib/node_modules/netlify-cli +0ms
  @oclif/config loadJSON /usr/local/lib/node_modules/netlify-cli/package.json +0ms
  @oclif/config loadJSON /usr/local/lib/node_modules/netlify-cli/oclif.manifest.json +4ms
  @oclif/config:netlify-cli using manifest from /usr/local/lib/node_modules/netlify-cli/oclif.manifest.json +0ms
  @oclif/config reading user plugins pjson /Users/arunsathiya/.local/share/netlify-cli/package.json +0ms
  @oclif/config loadJSON /Users/arunsathiya/.local/share/netlify-cli/package.json +3ms
  @oclif/config loading plugins [ '@oclif/plugin-not-found',
  '@oclif/plugin-plugins',
  '@oclif/plugin-help' ] +2ms
  @oclif/config reading core plugin /usr/local/lib/node_modules/netlify-cli/node_modules/@oclif/plugin-not-found +0ms
  @oclif/config loadJSON /usr/local/lib/node_modules/netlify-cli/node_modules/@oclif/plugin-not-found/package.json +5ms
  @oclif/config reading core plugin /usr/local/lib/node_modules/netlify-cli/node_modules/@oclif/plugin-plugins +0ms
  @oclif/config loadJSON /usr/local/lib/node_modules/netlify-cli/node_modules/@oclif/plugin-plugins/package.json +0ms
  @oclif/config reading core plugin /usr/local/lib/node_modules/netlify-cli/node_modules/@oclif/plugin-help +0ms
  @oclif/config loadJSON /usr/local/lib/node_modules/netlify-cli/node_modules/@oclif/plugin-help/package.json +1ms
  @oclif/config loadJSON /usr/local/lib/node_modules/netlify-cli/node_modules/@oclif/plugin-not-found/oclif.manifest.json +0ms
  @oclif/config loadJSON /usr/local/lib/node_modules/netlify-cli/node_modules/@oclif/plugin-plugins/oclif.manifest.json +1ms
  @oclif/config loadJSON /usr/local/lib/node_modules/netlify-cli/node_modules/@oclif/plugin-not-found/.oclif.manifest.json +0ms
  @oclif/config loadJSON /usr/local/lib/node_modules/netlify-cli/node_modules/@oclif/plugin-help/oclif.manifest.json +1ms
  @oclif/config:@oclif/plugin-plugins using manifest from /usr/local/lib/node_modules/netlify-cli/node_modules/@oclif/plugin-plugins/oclif.manifest.json +0ms
  @oclif/config:@oclif/plugin-not-found using manifest from /usr/local/lib/node_modules/netlify-cli/node_modules/@oclif/plugin-not-found/.oclif.manifest.json +0ms
  @oclif/config:@oclif/plugin-help using manifest from /usr/local/lib/node_modules/netlify-cli/node_modules/@oclif/plugin-help/oclif.manifest.json +0ms
  @oclif/config config done +8ms
  @oclif/config start init hook +1ms
  @oclif/config loadJSONSync /usr/local/lib/node_modules/netlify-cli/tsconfig.json +4ms
  netlify:netlify-cli:hooks:init start /usr/local/lib/node_modules/netlify-cli/src/hooks/init +0ms
  netlify:netlify-cli:hooks:init done +50ms
  @oclif/config init hook done +52ms
  netlify init version: @oclif/command@1.5.8 argv: [ 'deploy' ] +0ms
  @oclif/config runCommand deploy [] +9ms
  @oclif/config loadJSONSync /usr/local/lib/node_modules/netlify-cli/tsconfig.json +60ms
  @oclif/config loadJSONSync /usr/local/lib/node_modules/netlify-cli/tsconfig.json +0ms
  @oclif/config:netlify-cli require /usr/local/lib/node_modules/netlify-cli/src/commands/deploy.js +75ms
  @oclif/config start prerun hook +3s
  @oclif/config prerun hook done +2ms
Error: Not Found
    at Object.error (/usr/local/lib/node_modules/netlify-cli/node_modules/@oclif/errors/lib/index.js:22:17)
    at DeployCommand.error (/usr/local/lib/node_modules/netlify-cli/node_modules/@oclif/command/lib/command.js:47:23)
    at DeployCommand.run (/usr/local/lib/node_modules/netlify-cli/src/commands/deploy.js:57:14)
    at process.internalTickCallback (internal/process/next_tick.js:77:7)
➜  drum-kit git:(master) ✗ ls
index.html
➜  drum-kit git:(master) ✗ netlify deploy
 ›   Error: Not Found
```

I haven't attempted to run `netlify link` so far, as suggested here https://github.com/netlify/cli/issues/180#issuecomment-444224316 - as my understanding is that it's required only when a local site has to be linked to an existing site online on Netlify.

Any ideas to fix this would be fantastic. Thanks for taking a look! 

**- Do you want to request a *feature* or report a *bug*?**

Report a bug

**- What is the current behavior?**

`netlify deploy` results in `Error: Not Found`

**- If the current behavior is a bug, please provide the steps to reproduce.**

- Start with a folder with a `index.html` file
- Run `netlify deploy`

**- What is the expected behavior?**

Site creation flow appears.

**- Please mention your node.js, and operating system version.**

- Node version - v11.6.0
- macOS 10.14.2 - Mac OS Mojave

**Comment by arunsathiya** [comment]
I might have an update to this. I deleted the entire parent folder of the root folder, created new folder and used `netlify deploy`. This time it works.

I guess I can close this GitHub issue at this time, but assuming devs might want to see what happened here, I am leaving this open.
