### ISSUE TITLE
Can't upgrade due to chalk issue

### ISSUE THREAD

**Issue by cfjedimaster** [netlify/cli#2266]
**Describe the bug**

Trying to install the latest and I get an error:

```
npm ERR! code 1
npm ERR! path /home/ray/.nvm/versions/node/v14.16.0/lib/node_modules/netlify-cli
npm ERR! command failed
npm ERR! command sh -c node ./scripts/postinstall.js
npm ERR! internal/modules/cjs/loader.js:883
npm ERR!   throw err;
npm ERR!   ^
npm ERR!
npm ERR! Error: Cannot find module 'chalk'
npm ERR! Require stack:
npm ERR! - /home/ray/.nvm/versions/node/v14.16.0/lib/node_modules/netlify-cli/scripts/postinstall.js
npm ERR!     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
npm ERR!     at Function.Module._load (internal/modules/cjs/loader.js:725:27)
npm ERR!     at Module.require (internal/modules/cjs/loader.js:952:19)
npm ERR!     at require (internal/modules/cjs/helpers.js:88:18)
npm ERR!     at Object.<anonymous> (/home/ray/.nvm/versions/node/v14.16.0/lib/node_modules/netlify-cli/scripts/postinstall.js:1:15)
npm ERR!     at Module._compile (internal/modules/cjs/loader.js:1063:30)
npm ERR!     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
npm ERR!     at Module.load (internal/modules/cjs/loader.js:928:32)
npm ERR!     at Function.Module._load (internal/modules/cjs/loader.js:769:14)
npm ERR!     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12) {
npm ERR!   code: 'MODULE_NOT_FOUND',
npm ERR!   requireStack: [
npm ERR!     '/home/ray/.nvm/versions/node/v14.16.0/lib/node_modules/netlify-cli/scripts/postinstall.js'
npm ERR!   ]
npm ERR! }

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ray/.npm/_logs/2021-04-28T17_47_14_662Z-debug.log
```

**To Reproduce**

1. npm i -g netlify-cli

**Comment by erezrokah** [comment]
Hi @cfjedimaster, can you share the output of `npx envinfo --system --binaries --npmPackages netlify-cli --npmGlobalPackages netlify-cli`?

**Comment by cfjedimaster** [comment]
```

  System:
    OS: Linux 5.4 Ubuntu 20.04.2 LTS (Focal Fossa)
    CPU: (20) x64 Intel(R) Core(TM) i9-10900K CPU @ 3.70GHz
    Memory: 20.54 GB / 24.85 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 14.16.0 - ~/.nvm/versions/node/v14.16.0/bin/node
    npm: 7.6.1 - ~/.nvm/versions/node/v14.16.0/bin/npm
  npmGlobalPackages:
    netlify-cli: 3.17.0
```

**Comment by erezrokah** [comment]
Thanks @cfjedimaster, does `npm install -g netlify-cli@3.22.1` work?
This is one version before https://github.com/netlify/cli/pull/2248 was introduced

**Comment by cfjedimaster** [comment]
Yep, that worked ok.

**Comment by erezrokah** [comment]
Thanks, can you share which solution worked?

**Comment by cfjedimaster** [comment]
Oh sorry - didn't read well. I did the first thing, installing 3.22.1. I'm updating npm now. Would you like me to try to get latest again after?

**Comment by cfjedimaster** [comment]
I figured it was harmless so I did. ;) So latest npm let me install netlify-cli w/o specifying a version.

**Comment by erezrokah** [comment]
Thank you @cfjedimaster for the quick follow ups and sharing the solution(s). Closing the issue.
