### ISSUE TITLE
Installation error from 3.22.0 to 3.24.3; Error: Cannot find module 'chalk';

### ISSUE THREAD

**Issue by nikahmadz** [netlify/cli#2280]
**Describe the bug**

I'm trying to update `netlify-cli` from `3.22.0 to 3.24.3` and got this error:

**CLI Output**

```
>npm i -g netlify-cli
npm ERR! code 1
npm ERR! path C:\Users\...\npm\node_modules\netlify-cli
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c node ./scripts/postinstall.js
npm ERR! internal/modules/cjs/loader.js:883
npm ERR!   throw err;
npm ERR!   ^
npm ERR!
npm ERR! Error: Cannot find module 'chalk'
npm ERR! Require stack:
npm ERR! - C:\Users\...\npm\node_modules\netlify-cli\scripts\postinstall.js
npm ERR!     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
npm ERR!     at Function.Module._load (internal/modules/cjs/loader.js:725:27)
npm ERR!     at Module.require (internal/modules/cjs/loader.js:952:19)
npm ERR!     at require (internal/modules/cjs/helpers.js:88:18)
npm ERR!     at Object.<anonymous> (C:\Users\...\npm\node_modules\netlify-cli\scripts\postinstall.js:1:15)
npm ERR!     at Module._compile (internal/modules/cjs/loader.js:1063:30)
npm ERR!     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
npm ERR!     at Module.load (internal/modules/cjs/loader.js:928:32)
npm ERR!     at Function.Module._load (internal/modules/cjs/loader.js:769:14)
npm ERR!     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12) {
npm ERR!   code: 'MODULE_NOT_FOUND',
npm ERR!   requireStack: [
npm ERR!     'C:\\Users\\...\\npm\\node_modules\\netlify-cli\\scripts\\postinstall.js'
npm ERR!   ]
npm ERR! }

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\...-debug.log
```

**To Reproduce**

1. Run `npm i -g netlify-cli`
2. See that the CLI exits with an error

**Configuration**

- `netlify.toml`.

```
[build]
  functions = "__functions"
  publish = "__site"

[context.dev.environment]
  VAR = 'dev-var'

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options  = "DENY"
    X-XSS-Protection = "1; mode=block"
```

```bash
npx envinfo --system --binaries --npmPackages netlify-cli --npmGlobalPackages netlify-cli
```
```
  System:
    OS: Windows 10 10.0.19042
    CPU: (4) x64 Intel(R) Core(TM) i5-4200U CPU @ 1.60GHz
    Memory: 3.51 GB / 7.89 GB
  Binaries:
    Node: 14.15.1 - ...\nodejs\node.EXE
    Yarn: 1.22.10 - ...\node_modules\.bin\yarn.CMD
    npm: 7.8.0 - ...\nodejs\npm.CMD
  npmPackages:
    netlify-cli: ^3.13.10 => 3.13.10
```

**Expected behavior**

Update without error.

**Additional context**

- N/A -

**Comment by eduardoboucas** [comment]
This seems to be a duplicate of #2266. Can you try [these suggestions](https://github.com/netlify/cli/issues/2266#issuecomment-828690232) and let me know if that helps?

**Comment by erezrokah** [comment]
Hi @nikahmadz, can you try upgrading yout `npm` version per this issue https://github.com/netlify/cli/issues/2266

1. `npm install -g npm`
2. `npm install -g netlify-cli`

**Comment by nikahmadz** [comment]
> This seems to be a duplicate of #2266. Can you try [these suggestions](https://github.com/netlify/cli/issues/2266#issuecomment-828690232) and let me know if that helps?

Sorry, isn't `npm install -g netlify-cli@3.22.1` means upgrading to `3.22.1`?  how about `3.24.3` ?

**Comment by nikahmadz** [comment]
Ok got it solved! Thanks
I upgrade npm before update netlify-cli.
```
> npm i -g npm
> npm i -g netlify-cli
```
