### ISSUE TITLE
netlify throws an error if git is not installed

### ISSUE THREAD

**Issue by streaps** [netlify/cli#28]
I don't know if this is a bug report or a feature request.

I tried netlify-cli on a bare bone alpine linux and forgot to install the git package first. If netlify cannot spawn the git command, it throws this error. A more user friendly error message would be nice, something like: "git command not found, please install git".

```
# netlify init -m
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: spawn git ENOENT
    at exports._errnoException (util.js:1018:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:367:16)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
    at Module.runMain (module.js:606:11)
    at run (bootstrap_node.js:390:7)
    at startup (bootstrap_node.js:150:9)
    at bootstrap_node.js:505:3
```

**Comment by bcomnes** [comment]
Git is required for some repo interactions.  Leaving this open to verify what happens on the 2.0.0 branch.

**Comment by erezrokah** [comment]
Closing this as stale, please re-open if still relevant
