### ISSUE TITLE
Cannot read property 'join' of undefined

### ISSUE THREAD

**Issue by eddyoc** [netlify/cli#3050]
Run netllfy project locally using `netlify dev` on `netlify-cli@5.4.1` installed globally.

The (relevant) output is as follows

◈ Loaded function test.
◈ Functions server is listening on 56559
◈ Starting Netlify Dev with Create React App

However when I hit this function using postman or some other HTTP client the instance crashes with the following error

```
Request from ::1: GET /.netlify/functions/test
TypeError: Cannot read property 'join' of undefined
    at formatLambdaLocalError (/Users/eddyoc/.config/yarn/global/node_modules/netlify-cli/src/lib/functions/synchronous.js:36:100)
    at handleErr (/Users/eddyoc/.config/yarn/global/node_modules/netlify-cli/src/lib/functions/synchronous.js:40:55)
    at handleSynchronousFunction (/Users/eddyoc/.config/yarn/global/node_modules/netlify-cli/src/lib/functions/synchronous.js:17:12)
    at handler (/Users/eddyoc/.config/yarn/global/node_modules/netlify-cli/src/lib/functions/server.js:102:7)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
TypeError: Cannot read property 'join' of undefined
    at formatLambdaLocalError (/Users/eddyoc/.config/yarn/global/node_modules/netlify-cli/src/lib/functions/synchronous.js:36:100)
    at handleErr (/Users/eddyoc/.config/yarn/global/node_modules/netlify-cli/src/lib/functions/synchronous.js:40:55)
    at handleSynchronousFunction (/Users/eddyoc/.config/yarn/global/node_modules/netlify-cli/src/lib/functions/synchronous.js:17:12)
    at handler (/Users/eddyoc/.config/yarn/global/node_modules/netlify-cli/src/lib/functions/server.js:102:7)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

This function works perfectly when deployed on netlify. It is a hello world function with no side effects.

**Comment by erezrokah** [comment]
Hi @eddyoc, do you mind sharing a reproduction scenario/the code of your function?

Looks like the offending code is here:
https://github.com/netlify/cli/blob/67c98a2355d11ef37179f8cb87bfb55c79038700/src/lib/functions/synchronous.js#L36

so it'd be great to know why we don't receive an error instance as expected.

**Comment by eddyoc** [comment]
I have `directory = "functions"` in my `netlify.toml`
I have a file` functions/test.js` having the contents
```
exports.handler = async function(event, context, callback) {
  const body = JSON.stringify({ message: 'hello world' });

  return callback(null, {
    statusCode: 200,
    body,
  })
};
```
I have installed several different versions of `netlify-cli` using `yarn`
I run locally using `yarn netlify dev`
The app starts up without error containing output line
`◈ Loaded function test.`
The app loads successfully on port 8888
I then perform a `GET` on endpoint `localhost:8888/.netlify/functions/test` using postman or any other client
The netlify instance crashes with error 
```
Request from ::1: GET /.netlify/functions/test?none=true
TypeError: Cannot read property 'join' of undefined
    at formatLambdaLocalError (/Users/eddyoc/development/crypto-mint/node_modules/netlify-cli/src/lib/functions/synchronous.js:36:100)
```

I have tried several older versions of `netlify-cli`. All exhibit the same behaviour.

**Comment by erezrokah** [comment]
Hi @eddyoc, it seems you're using an `async` function, but with a callback pattern.
Can you try:
```
exports.handler = function(event, context, callback) {
  const body = JSON.stringify({ message: 'hello world' });

  return callback(null, {
    statusCode: 200,
    body,
  })
};
```

or:
```
exports.handler = async function(event, context) {
  const body = JSON.stringify({ message: 'hello world' });

  return {
    statusCode: 200,
    body,
  }
};
```

**Comment by eddyoc** [comment]
I have tried both options outlined above. Using callback without async. And using async with a normal return statement. Examples exactly as per previous post.

The result is always the same ```TypeError: Cannot read property 'join' of undefined```

**Comment by erezrokah** [comment]
Hi @eddyoc, do you mind sharing a public repo reproducing this issue? Those exact functions worked for me so I'm probably missing something here.

Also, can you make sure to update to the latest CLI version via `npm install -g netlify-cli` and share the output of `npx envinfo --system --binaries --npmPackages netlify-cli --npmGlobalPackages netlify-cli`?

**Comment by sarahetter** [comment]
Closing as stale. Please re-open if needed
