### ISSUE TITLE
Proxy support is broken

### ISSUE THREAD

**Issue by zmwangx** [netlify/cli#3115]
**Describe the bug**

Proxy support was introduced in #1215, but it is currently broken.

**To Reproduce**

1. Somehow make api.netlify.com unavailable, e.g. by being on a closed network where a proxy is required. For reproduction purposes, one can force this by modifying `/etc/hosts` and pointing api.netlify.com to a local container / VM where we spin up a trivial HTTP server that simply stalls on any incoming request.
2. Have a proxy server set up, e.g. mitmproxy or Charles.
3. Run any command through a proxy, e.g. `HTTP_PROXY=http://localhost:8888 netlify login`.

At this point `netlify-cli` would simply stall, and if you monitor the proxy server you'll notice that no request is going through it.

**Configuration**

N/A.

**Expected behavior**

Any network request originating from netlify-cli should be proxied.

**CLI Output**

N/A.

**Additional context**

This happens because `getConfig` happens before the proxy is even configured (with `getAgent`)

https://github.com/netlify/cli/blob/7a55e9871059ac656096735d1c0369b4d473e07e/src/utils/command.js#L46-L57

`getConfig` calls `resolveConfig` which is `@netlify/config`.

https://github.com/netlify/cli/blob/7a55e9871059ac656096735d1c0369b4d473e07e/src/utils/command.js#L4

Looking at `@netlify/config`'s `resolveConfig`: https://github.com/netlify/build/blob/6813d73a21a6c4a6b99576c5b7bc60fae5d8bac4/packages/config/src/main.js#L32-L36 we see that there are API requests made at this stage unless `offline` is true. These requests obviously aren't going through the proxy.

I guess to actually fully support proxies you need to add proxy support to `@netlify/config` as well.

---

Knowing the cause of the issue, here's a risky workaround btw: just set `offline` to true in `src/utils/command.js`:

```diff
-    const cachedConfig = await this.getConfig({ cwd, state, token, ...apiUrlOpts })
+    const cachedConfig = await this.getConfig({ cwd, state, token, offline: true, ...apiUrlOpts })
```

One can hot edit this directly into `node_modules/netlify-cli/src/utils/command.js`. (Don't complain to me if anything breaks, obviously.)

---

Related: I believe #2016 is exactly this problem.

**Comment by erezrokah** [comment]
Thanks @zmwangx, I believe this is a duplicate of https://github.com/netlify/cli/issues/2399, but I'm closing #2399 in favor of this one since due to the more detailed description here

**Comment by mordonez** [comment]
This issue is still happening today with recent versions.

We’re running Netlify CLI behind an explicit HTTP/HTTPS proxy. Even though HTTP_PROXY / HTTPS_PROXY are set, the CLI fails with fetch failed when retrieving site extensions (getExtensions, getSiteInfo). This happens even for basic commands like netlify status.

Tested with Node.js 20, 22, and 25 (currently using Node 22, the recommended version) and netlify-cli 23.13.3.
We also tried forcing proxy support via global-agent, without success.

output

```
/srv # node --version
v22.21.1

/srv # ./node_modules/.bin/netlify --version
netlify-cli/23.13.3 linux-x64 node-v22.21.1

/srv # env
HTTPS_PROXY=http://PROXY-IP
NODE_VERSION=22.21.1
HOSTNAME=
YARN_VERSION=1.22.22
SHLVL=1
HOME=/root
OLDPWD=/root
https_proxy=http://:PROXY-IP
http_proxy=http://:PROXY-IP
NETLIFY_AUTH_TOKEN=xxxx
TERM=xterm
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
PWD=/srv
HTTP_PROXY=http://PROXY-IP

/srv # ./node_modules/.bin/netlify status --debug
[project.ts]: detectFrameworks
[project.ts]: detectBuildSystem
[project.ts]: detectWorkspaces
[project.ts]: detectPackageManager
[project.ts]: detectFrameworksInPath - undefined

❯ Initial build environment
context: dev
cwd: /srv
featureFlags: 

mode: cli
repositoryRoot: /srv
siteId: 
›   Warning: Error: Failed retrieving extensions for site : fetch failed. Double-check your login status with ‘netlify status’ or contact support with details of your error.
›       at getError (file:///srv/node_modules/@netlify/config/lib/error.js:14:16)
›       at throwUserError (file:///srv/node_modules/@netlify/config/lib/error.js:4:20)
›       at getExtensions (file:///srv/node_modules/@netlify/config/lib/api/site_info.js:149:16)
›       at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
›       at async Promise.all (index 2)
›       at async getSiteInfo (file:///srv/node_modules/@netlify/config/lib/api/site_info.js:41:46)
›       at async resolveConfig (file:///srv/node_modules/@netlify/config/lib/main.js:51:33)
›       at async BaseCommand.getConfig (file:///srv/node_modules/netlify-cli/dist/commands/base-command.js:565:20)
›       at async BaseCommand.init (file:///srv/node_modules/netlify-cli/dist/commands/base-command.js:468:30)
›       at async Object.callback (file:///srv/node_modules/netlify-cli/dist/commands/base-command.js:166:13)
›   Warning: Failed to resolve config, falling back to offline resolution

──────────────────────┐
Current Netlify User │
──────────────────────┘
Name:  xxxxxx
Email: xxxxxxx

────────────────────┐
Netlify Project Info  │
────────────────────┘
Admin URL:   undefined
Project URL: undefined
Project Id:  xxxx-xxx-xxx-xxx
```

This looks like some internal fetch calls are still not proxy-aware.
