### ISSUE TITLE
Error: Stream body too big

### ISSUE THREAD

**Issue by byteshiva** [netlify/cli#3513]
I'm getting the below error while running the netlify functions on the local machine.

Am I missing something here?

```
Error: Stream body too big
    at IncomingMessage.onData (/home/xyz/.asdf/installs/nodejs/16.2.0/.npm/lib/node_modules/netlify-cli/src/utils/create-stream-promise.js:24:16)
    at IncomingMessage.emit (node:events:365:28)
    at IncomingMessage.emit (node:domain:470:12)
    at addChunk (node:internal/streams/readable:314:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at IncomingMessage.Readable.push (node:internal/streams/readable:228:10)
    at HTTPParser.parserOnBody (node:_http_common:140:24)
Error: Stream body too big
    at IncomingMessage.onData (/home/xyz/.asdf/installs/nodejs/16.2.0/.npm/lib/node_modules/netlify-cli/src/utils/create-stream-promise.js:24:16)
    at IncomingMessage.emit (node:events:365:28)
    at IncomingMessage.emit (node:domain:470:12)
    at addChunk (node:internal/streams/readable:314:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at IncomingMessage.Readable.push (node:internal/streams/readable:228:10)
    at HTTPParser.parserOnBody (node:_http_common:140:24)

/home/xyz/.asdf/installs/nodejs/16.2.0/.npm/lib/node_modules/netlify-cli/node_modules/netlify-redirector/lib/redirects.js:116
      throw ex;
      ^
abort({}) at Error: 
    at jsStackTrace (/home/xyz/.asdf/installs/nodejs/16.2.0/.npm/lib/node_modules/netlify-cli/node_modules/netlify-redirector/lib/redirects.js:1070:13)
    at stackTrace (/home/xyz/.asdf/installs/nodejs/16.2.0/.npm/lib/node_modules/netlify-cli/node_modules/netlify-redirector/lib/redirects.js:1087:12)
    at process.abort (/home/xyz/.asdf/installs/nodejs/16.2.0/.npm/lib/node_modules/netlify-cli/node_modules/netlify-redirector/lib/redirects.js:8502:44)
    at process.emit (node:events:365:28)
    at processEmit [as emit] (/home/xyz/.asdf/installs/nodejs/16.2.0/.npm/lib/node_modules/netlify-cli/node_modules/signal-exit/index.js:175:34)
    at emit (node:internal/process/promises:136:22)
    at processPromiseRejections (node:internal/process/promises:242:25)
    at processTicksAndRejections (node:internal/process/task_queues:97:32)
```

**Comment by tinfoil-knight** [comment]
@byteshiva Regarding the first issue, could you check how large was the data payload?

Netlify Functions will throw errors on data sizes larger than 6MB since AWS Lambda Functions (which Netlify Functions is based on top of) has this limit for function invocation payloads as mentioned in this page: https://docs.aws.amazon.com/lambda/latest/dg/gettingstarted-limits.html

**Comment by byteshiva** [comment]
> @byteshiva Regarding the first issue, could you check how large was the data payload?
> 
> Netlify Functions will throw errors on data sizes larger than 6MB since AWS Lambda Functions (which Netlify Functions is based on top of) has a 6MB limit for function invocation payloads as mentioned in this page: https://docs.aws.amazon.com/lambda/latest/dg/gettingstarted-limits.html
> 
> The error comes from here:
> 
> https://github.com/netlify/cli/blob/9b293defb06545ae5f825f6121732d9e92c29d9e/src/utils/create-stream-promise.js#L24

@tinfoil-knight  - Why limit the upload size when one could use [localstack](https://github.com/localstack/localstack) to run Lambda functions locally without connecting to AWS.

It threw an error when I tried to upload file size of 3.9MB.

**Comment by tinfoil-knight** [comment]
I looked a bit more, I'm probably wrong about my previous assumption. Apologies.

If possible could you provide a public repo with the function you were running?

**Comment by tinfoil-knight** [comment]
@byteshiva 
I took a simple function that takes in file from the request body and just writes it to the local system.

`functions/hello-world.js`

```
const fs = require("fs");

const handler = async (event) => {
  try {
    const image = event.body;
    var bitmap = Buffer.from(image, "base64");
    fs.writeFileSync("./image.png", bitmap);
    const subject = event.queryStringParameters.name || "World";
    return {
      statusCode: 200,
      body: JSON.stringify({ message: `Hello ${subject}` }),
    };
  } catch (error) {
    return { statusCode: 500, body: error.toString() };
  }
};

module.exports = { handler };

```

On file sizes below 6MB encoded with base64, I'm able to receive and write the file successfully but post that I get the error: `PayloadTooLargeError: request entity too large`

I was using the `functions:serve` command to run the functions server.

**Comment by tinfoil-knight** [comment]
@byteshiva 
I wrote a small function to just write the uploaded file to the local filesystem.

```
const fs = require("fs");

const handler = async (event) => {
  try {
    const image = event.body;
    const bitmap = Buffer.from(image, "base64");
    fs.writeFileSync("./image.png", bitmap);
    const subject = event.queryStringParameters.name || "World";
    return {
      statusCode: 200,
      body: JSON.stringify({ message: `Hello ${subject}` }),
    };
  } catch (error) {
    return { statusCode: 500, body: error.toString() };
  }
};

module.exports = { handler };
```

I tried files ranging smaller and larger than 6MB. Files below 6MB were uploaded successfully and written to my filesystem. For files above 6MB, I got the `Error: Stream body too big` as expected.

I'm not able to reproduce the error on files of sizes smaller than 6MB.

**Comment by tinfoil-knight** [comment]
> @tinfoil-knight - Why limit the upload size when one could use localstack to run Lambda functions locally without connecting to AWS.

@byteshiva It'd be inconsistent if your functions ran locally but failed when you deployed and tried them on a production environment. IMO the production and local environment should behave as similar as possible to avoid errors in production.

**Comment by tinfoil-knight** [comment]
@erezrokah Sidenote: 
Here:
https://github.com/netlify/cli/blob/9b293defb06545ae5f825f6121732d9e92c29d9e/src/utils/proxy.js#L364

The author intends to pass the `BYTES_LIMIT` constant for the `bytesLimit` parameter. But due to the ordering of the parameters, either the constant: `BYTES_LIMIT` is named incorrectly or the argument is being passed wrongly.
See:
https://github.com/netlify/cli/blob/9b293defb06545ae5f825f6121732d9e92c29d9e/src/utils/create-stream-promise.js#L3

**Comment by tinfoil-knight** [comment]
@erezrokah I think the variable is named incorrectly in the above lines. Should I rename it to `REQUEST_TIMEOUT`?

**Comment by serhalp** [comment]
Marking this as stale as it is is several years old. Please feel free to reopen if you are still having issues.
