### ISSUE TITLE
netlify dev -d flag is not working 

### ISSUE THREAD

**Issue by surma** [netlify/cli#359]
**- Do you want to request a *feature* or report a *bug*?**
Bug

**- What is the current behavior?**
```
$ netlify dev -c "npm run build" -d "build"`
◈ Netlify Dev ◈
Error: Expected an integer but received: build
    at Object.parse (~/.nvm/versions/node/v12.4.0/lib/node_modules/netlify-cli/node_modules/@oclif/parser/lib/flags.js:17:19)
    at Parser._flags (~/.nvm/versions/node/v12.4.0/lib/node_modules/netlify-cli/node_modules/@oclif/parser/lib/parse.js:152:49)
    at Parser.parse (~/.nvm/versions/node/v12.4.0/lib/node_modules/netlify-cli/node_modules/@oclif/parser/lib/parse.js:113:28)
    at Object.parse (~/.nvm/versions/node/v12.4.0/lib/node_modules/netlify-cli/node_modules/@oclif/parser/lib/index.js:25:27)
    at DevCommand.parse (~/.nvm/versions/node/v12.4.0/lib/node_modules/netlify-cli/node_modules/@oclif/command/lib/command.js:83:41)
    at DevCommand.run (~/.nvm/versions/node/v12.4.0/lib/node_modules/netlify-cli/node_modules/netlify-dev-plugin/src/commands/dev/index.js:172:26)
    at DevCommand._run (~/.nvm/versions/node/v12.4.0/lib/node_modules/netlify-cli/node_modules/@oclif/command/lib/command.js:44:31)
```
**- If the current behavior is a bug, please provide the steps to reproduce.**
See above

**- What is the expected behavior?**
The `-d` flag should allow me to specify the directory my output is in. Surely that ought to be a string, not an integer :D

**- Please mention your node.js, and operating system version.**
netlify-cli/2.11.27 darwin-x64 node-v12.4.0

**Comment by DavidWells** [comment]
Hey @surma 

Thanks for the report. 

Indeed looks like a problem in the dev plugin. https://github.com/netlify/netlify-dev-plugin/blob/master/src/commands/dev/index.js#L317 

Fixing this and should have a release out later today

**Comment by DavidWells** [comment]
Fixed via netlify-cli@2.11.28

**Comment by sw-yx** [comment]
surma's log output also indicates he is running an old version of netlify dev. if he was a beta user he may need to break the symlink

**Comment by DavidWells** [comment]
@surma you all good with CLI version `netlify-cli@2.11.28+`?

Holler if you see anymore issues!

**Comment by surma** [comment]
Yes, this particular issue is fine. I’m about to open more. Apologies 😅

**Comment by sw-yx** [comment]
bring it
