### ISSUE TITLE
Unable to install netlify-cli 8.1.4 with Yarn Plug'n'Play enabled

### ISSUE THREAD

**Issue by vsaarinen** [netlify/cli#3840]
**Describe the bug**

When trying to upgrade to netlify-cli 8.1.4 in a project that uses Yarn Plug'n'Play, the build step fails with the following log:

```
# This file contains the result of Yarn building a package (netlify-cli@npm:8.1.4)
# Script name: postinstall


Success! Netlify CLI has been installed!

Your device is now configured to use Netlify CLI to deploy and manage your Netlify sites.

Next steps:

  netlify init     Connect or create a Netlify site from current directory
  netlify deploy   Deploy the latest changes to your Netlify site

For more information on the CLI run netlify help
Or visit the docs at https://cli.netlify.com

Error: ENOTDIR: not a directory, stat '/Users/ville/Repos/web/.yarn/cache/@netlify-config-npm-16.0.7-99effdf6eb-0f139b1f70.zip/node_modules/@netlify/config/src/api/node_modules/netlify'
    at statSync (fs.js:1131:3)
    at tryStatSync (internal/modules/esm/resolve.js:109:13)
    at packageResolve (internal/modules/esm/resolve.js:662:18)
    at moduleResolve (internal/modules/esm/resolve.js:728:18)
    at Loader.defaultResolve [as _resolve] (internal/modules/esm/resolve.js:842:11)
    at Loader.resolve (internal/modules/esm/loader.js:89:40)
    at Loader.getModuleJob (internal/modules/esm/loader.js:242:28)
    at Loader.import (internal/modules/esm/loader.js:177:28)
    at importModuleDynamically (internal/modules/cjs/loader.js:1028:27)
    at exports.importModuleDynamicallyCallback (internal/process/esm_loader.js:30:14) {
  errno: -20,
  syscall: 'stat',
  code: 'ENOTDIR',
  path: '/Users/ville/Repos/web/.yarn/cache/@netlify-config-npm-16.0.7-99effdf6eb-0f139b1f70.zip/node_modules/@netlify/config/src/api/node_modules/netlify'
}
Error: ENOTDIR: not a directory, stat '/Users/ville/Repos/web/.yarn/cache/@netlify-config-npm-16.0.7-99effdf6eb-0f139b1f70.zip/node_modules/@netlify/config/src/api/node_modules/netlify'
    at statSync (fs.js:1131:3)
    at tryStatSync (internal/modules/esm/resolve.js:109:13)
    at packageResolve (internal/modules/esm/resolve.js:662:18)
    at moduleResolve (internal/modules/esm/resolve.js:728:18)
    at Loader.defaultResolve [as _resolve] (internal/modules/esm/resolve.js:842:11)
    at Loader.resolve (internal/modules/esm/loader.js:89:40)
    at Loader.getModuleJob (internal/modules/esm/loader.js:242:28)
    at Loader.import (internal/modules/esm/loader.js:177:28)
    at importModuleDynamically (internal/modules/cjs/loader.js:1028:27)
    at exports.importModuleDynamicallyCallback (internal/process/esm_loader.js:30:14) {
  errno: -20,
  syscall: 'stat',
  code: 'ENOTDIR',
  path: '/Users/ville/Repos/web/.yarn/cache/@netlify-config-npm-16.0.7-99effdf6eb-0f139b1f70.zip/node_modules/@netlify/config/src/api/node_modules/netlify'
}

/Users/ville/Repos/web/.yarn/cache/netlify-redirector-npm-0.2.1-6757cc04ec-991533d072.zip/node_modules/netlify-redirector/lib/redirects.js:116
      throw ex;
      ^
abort({"errno":-20,"syscall":"stat","code":"ENOTDIR","path":"/Users/ville/Repos/web/.yarn/cache/@netlify-config-npm-16.0.7-99effdf6eb-0f139b1f70.zip/node_modules/@netlify/config/src/api/node_modules/netlify"}) at Error
    at jsStackTrace (/Users/ville/Repos/web/.yarn/cache/netlify-redirector-npm-0.2.1-6757cc04ec-991533d072.zip/node_modules/netlify-redirector/lib/redirects.js:1070:13)
    at stackTrace (/Users/ville/Repos/web/.yarn/cache/netlify-redirector-npm-0.2.1-6757cc04ec-991533d072.zip/node_modules/netlify-redirector/lib/redirects.js:1087:12)
    at process.abort (/Users/ville/Repos/web/.yarn/cache/netlify-redirector-npm-0.2.1-6757cc04ec-991533d072.zip/node_modules/netlify-redirector/lib/redirects.js:8502:44)
    at process.emit (events.js:400:28)
    at process.emit (domain.js:475:12)
    at processPromiseRejections (internal/process/promises.js:245:33)
    at processTicksAndRejections (internal/process/task_queues.js:96:32)
(Use `node --trace-uncaught ...` to show where the exception was thrown)
```

Installing version 8.1.3 of netlify-cli works fine.

**To Reproduce**

1. In a project that uses Yarn PnP, run `yarn up netlify-cli@8.1.4`
2. See that Yarn fails with an error

**Configuration**

N/A

**Expected behavior**

I would expect the installation to work-.

**CLI Output**

N/A

**Additional context**

N/A

**Comment by lukasholzer** [comment]
@vsaarinen `yarn up` does not seem to be a regular command: `error Command "up" not found.` 

using yarn version: `1.22.17` 

can you maybe specify it a little bit clearer or do you have an example repo we can clone to try to reproduce it?

**Comment by lukasholzer** [comment]
@vsaarinen can you try our rc release out if it works for you? `netlify-cli@8.1.5-rc.1`

**Comment by vsaarinen** [comment]
> @vsaarinen can you try out our rc release and test if it works for you? `netlify-cli@8.1.5-rc.1`

Yep, this issue seems to be fixed in the RC. 

I started running into more Yarn PnP -related issues when running the CLI command, however, but I'll make a separate issue about them. It seems that `netlify` version 10 and/or `@netlify/build` version 20 are not compatible with Yarn PnP.

**Comment by lukasholzer** [comment]
Yea I assume this is due to the lack of ESM support inside yarn pnp and we are now switching our packages to ESModules as we need to, to updated some of our dependencies that are already ESM for security fixes

**Comment by vsaarinen** [comment]
Should a switch to ESM be a major version change since it seems like a breaking change? At least for us it may mean that we can't upgrade to that version since we're using Yarn PnP.

**Comment by lukasholzer** [comment]
@vsaarinen we actually did that on the config. https://github.com/netlify/build/releases/tag/config-v17.0.0

But as commonjs can import ESModules through dynamic imports there it should not be a breaking thing on the CLI. https://github.com/netlify/cli/commit/ede351485bffe8d2e1d0a8a5374cd435a77fe685

I'm only wondering what yarn pnp does differently to have some issues (especially in a postinstall script where those are loaded 🤔 

Maybe @ehmicky has an idea

**Comment by vsaarinen** [comment]
It seems the build is still broken on versions `8.1.5` to `8.1.7`.

**Comment by lukasholzer** [comment]
@vsaarinen yea the PR is not merged yet had to wait for a new review: https://github.com/netlify/cli/pull/3841

**Comment by lukasholzer** [comment]
The fix is currently only inside an rc version

**Comment by lukasholzer** [comment]
Going to release it now ;)

**Comment by lukasholzer** [comment]
Is released now under https://github.com/netlify/cli/releases/tag/v8.1.8

**Comment by vsaarinen** [comment]
Thanks, that version fixes the build issue. But now I'm running into further issues due to Yarn PnP, even after enabling experimental ESM support and adding `netlify`:

```
$ yarn netlify deploy
Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'netlify' imported from /Users/ville/Repos/web/.yarn/unplugged/netlify-cli-npm-8.1.8-13d7da449b/node_modules/netlify-cli/src/commands/base-command.js
Did you mean to import netlify-npm-10.0.0-ece5d3e4fa-12c14075e4.zip/node_modules/netlify/src/index.js?
    at new NodeError (internal/errors.js:322:7)
    at packageResolve (internal/modules/esm/resolve.js:687:9)
    at moduleResolve (internal/modules/esm/resolve.js:728:18)
    at Loader.defaultResolve [as _resolve] (internal/modules/esm/resolve.js:842:11)
    at Loader.resolve (internal/modules/esm/loader.js:89:40)
    at Loader.getModuleJob (internal/modules/esm/loader.js:242:28)
    at Loader.import (internal/modules/esm/loader.js:177:28)
    at importModuleDynamically (internal/modules/cjs/loader.js:1028:27)
    at exports.importModuleDynamicallyCallback (internal/process/esm_loader.js:30:14)
    at Object.<anonymous> (/Users/ville/Repos/web/.yarn/unplugged/netlify-cli-npm-8.1.8-13d7da449b/node_modules/netlify-cli/src/commands/base-command.js:10:18) {
  code: 'ERR_MODULE_NOT_FOUND'
}
Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'netlify' imported from /Users/ville/Repos/web/.yarn/unplugged/netlify-cli-npm-8.1.8-13d7da449b/node_modules/netlify-cli/src/commands/base-command.js
Did you mean to import netlify-npm-10.0.0-ece5d3e4fa-12c14075e4.zip/node_modules/netlify/src/index.js?
    at new NodeError (internal/errors.js:322:7)
    at packageResolve (internal/modules/esm/resolve.js:687:9)
    at moduleResolve (internal/modules/esm/resolve.js:728:18)
    at Loader.defaultResolve [as _resolve] (internal/modules/esm/resolve.js:842:11)
    at Loader.resolve (internal/modules/esm/loader.js:89:40)
    at Loader.getModuleJob (internal/modules/esm/loader.js:242:28)
    at Loader.import (internal/modules/esm/loader.js:177:28)
    at importModuleDynamically (internal/modules/cjs/loader.js:1028:27)
    at exports.importModuleDynamicallyCallback (internal/process/esm_loader.js:30:14)
    at Object.<anonymous> (/Users/ville/Repos/web/.yarn/unplugged/netlify-cli-npm-8.1.8-13d7da449b/node_modules/netlify-cli/src/commands/base-command.js:10:18) {
  code: 'ERR_MODULE_NOT_FOUND'
}

/Users/ville/Repos/web/.yarn/cache/netlify-redirector-npm-0.2.1-6757cc04ec-991533d072.zip/node_modules/netlify-redirector/lib/redirects.js:116
      throw ex;
      ^
abort({"code":"ERR_MODULE_NOT_FOUND"}) at Error
    at jsStackTrace (/Users/ville/Repos/web/.yarn/cache/netlify-redirector-npm-0.2.1-6757cc04ec-991533d072.zip/node_modules/netlify-redirector/lib/redirects.js:1070:13)
    at stackTrace (/Users/ville/Repos/web/.yarn/cache/netlify-redirector-npm-0.2.1-6757cc04ec-991533d072.zip/node_modules/netlify-redirector/lib/redirects.js:1087:12)
    at process.abort (/Users/ville/Repos/web/.yarn/cache/netlify-redirector-npm-0.2.1-6757cc04ec-991533d072.zip/node_modules/netlify-redirector/lib/redirects.js:8502:44)
    at process.emit (events.js:400:28)
    at processPromiseRejections (internal/process/promises.js:245:33)
    at processTicksAndRejections (internal/process/task_queues.js:96:32)
(Use `node --trace-uncaught ...` to show where the exception was thrown)
```

The only way I can get netlify-cli to work is to pin `netlify-cli` to `8.0.5` and add the following to `packages.json`:

```
  "resolutions": {
    "netlify": "9",
    "@netlify/config": "16.0.4",
    "@netlify/zip-it-and-ship-it": "5.1.0"
  }
```

Should I create a separate issue for this?

**Comment by vsaarinen** [comment]
I guess one way to solve this problem is to not have `netlify-cli` be a dependency of our project and install it globally (using npm) as a separate build step in our CI/CD system...

**Comment by lukasholzer** [comment]
Please yes If you would create a seperate issue it would be super awesome! :).

And yes having the CLI globally installed I guess would solve the issue 👍
