### ISSUE TITLE
[Android] Netlify dev failed with redirects/edge functions

### ISSUE THREAD

**Issue by McJoe21** [netlify/cli#4621]
### Describe the bug

```
Could not read downloaded binary
    at DenoBridge.downloadBinary (file:///data/data/com.termux/files/usr/lib/node_modules/netlify-cli/node_modules/@netlify/edge-bundler/dist/bridge.js:33:19)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async DenoBridge.getBinaryPath (file:///data/data/com.termux/files/usr/lib/node_modules/netlify-cli/node_modules/@netlify/edge-bundler/dist/bridge.js:116:32)
    at async Module.serve (file:///data/data/com.termux/files/usr/lib/node_modules/netlify-cli/node_modules/@netlify/edge-bundler/dist/server/server.js:52:5)
    at async prepareServer (/data/data/com.termux/files/usr/lib/node_modules/netlify-cli/src/lib/edge-functions/proxy.js:142:22)
Error: Could not read downloaded binary
    at DenoBridge.downloadBinary (file:///data/data/com.termux/files/usr/lib/node_modules/netlify-cli/node_modules/@netlify/edge-bundler/dist/bridge.js:33:19)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async DenoBridge.getBinaryPath (file:///data/data/com.termux/files/usr/lib/node_modules/netlify-cli/node_modules/@netlify/edge-bundler/dist/bridge.js:116:32)
    at async Module.serve (file:///data/data/com.termux/files/usr/lib/node_modules/netlify-cli/node_modules/@netlify/edge-bundler/dist/server/server.js:52:5)
    at async prepareServer (/data/data/com.termux/files/usr/lib/node_modules/netlify-cli/src/lib/edge-functions/proxy.js:142:22)

/data/data/com.termux/files/usr/lib/node_modules/netlify-cli/node_modules/netlify-redirector/lib/redirects.js:116
      throw ex;
      ^
abort({}) at Error
    at jsStackTrace (/data/data/com.termux/files/usr/lib/node_modules/netlify-cli/node_modules/netlify-redirector/lib/redirects.js:1070:13)
    at stackTrace (/data/data/com.termux/files/usr/lib/node_modules/netlify-cli/node_modules/netlify-redirector/lib/redirects.js:1087:12)
    at process.abort (/data/data/com.termux/files/usr/lib/node_modules/netlify-cli/node_modules/netlify-redirector/lib/redirects.js:8502:44)
    at process.emit (node:events:527:28)
    at processEmit [as emit] (/data/data/com.termux/files/usr/lib/node_modules/netlify-cli/node_modules/signal-exit/index.js:199:34)
    at emit (node:internal/process/promises:140:20)
    at processPromiseRejections (node:internal/process/promises:274:27)
    at processTicksAndRejections (node:internal/process/task_queues:97:32)
(Use `node --trace-uncaught ...` to show where the exception was thrown)
```

Here's the logs. I was trying to just get a dev environment running on my phone and it's not working.

### Steps to reproduce

```bash
netlify dev
```

### Configuration

```toml
[build]
publish = "public"
functions = "functions"

[[redirects]] 
from = "/api/*"
to= "/.netlify/functions/:splat"
status = 200

[dev]
port = 2222
```

### Environment

```
System:
    OS: android
    CPU: Unknown
    Memory: 1003.25 MB / 3.66 GB
  Binaries:
    Node: 17.9.0 - /data/data/com.termux/files/usr/bin/node
    npm: 8.10.0 - /data/data/com.termux/files/usr/bin/npm
  npmGlobalPackages:
    netlify-cli: 10.3.0
```

**Comment by gsperk** [comment]
I have had the same error running netlify dev since cli v 10.

System:
CentOS Linux release 7.9.2009 (Core) running in Vagrant 2.2.9 on Windows.

**Comment by jackiewmacharia** [comment]
A workaround for this error is to downgrade CLI to `v9.16.7` with `npm install netlify-cli@9.16.7 -g` while we work on a fix for it. Also worth noting is that v9 of CLI won't work with Edge Functions.

**Comment by cmarabate** [comment]
I have the same issue, please fix!

**Comment by novelnet** [comment]
Me too, just downgrading is working so far.

**Comment by jackiewmacharia** [comment]
@McJoe21 almost there, it will be soon!

**Comment by jackiewmacharia** [comment]
This is now fixed in v10.7.1 of CLI. Test it out by running: `npm install netlify-cli -g`. In case of any issues, do let me know here.

**Comment by McJoe21** [comment]
> This is now fixed in v10.7.1 of CLI. Test it out by running: `npm install netlify-cli -g`. In case of any issues, do let me know here.

Setting up the Edge Functions environment. This may take a couple of minutes.
 ›   Error: There was a problem setting up the Edge Functions environment. To try a manual installation, visit https://ntl.fyi/install-deno.

**Comment by jackiewmacharia** [comment]
@McJoe21 that error pops up if there's an issue with the automated Deno installation due to various reasons including unsupported platforms by Deno like linux-arch64. What this fix does is to make sure that this doesn't break the rest of `netlify dev` if Edge Functions functionality wasn't available. Are you able to use continue using `netlify dev` with a [serveless function](https://docs.netlify.com/functions/build-with-typescript/) for example?

**Comment by McJoe21** [comment]
> @McJoe21 that error pops up if there's an issue with the automated Deno installation due to various reasons including unsupported platforms by Deno like linux-arch64. What this fix does is to make sure that this doesn't break the rest of `netlify dev` if Edge Functions functionality wasn't available. Are you able to use continue using `netlify dev` with a [serveless function](https://docs.netlify.com/functions/build-with-typescript/) for example?

yes
