### ISSUE TITLE
`TypeError: (intermediate value).conflicts is not a function` during `yarn install` (yarn v1.22.19)

### ISSUE THREAD

**Issue by Jolg42** [netlify/cli#4747]
### Describe the bug

The CLI errors with `TypeError: (intermediate value).conflicts is not a function` during `yarn install`

See renovate PR updating the dependency where the failure was spotted
https://github.com/prisma/ecosystem-tests/pull/2864

Logs https://github.com/prisma/ecosystem-tests/runs/7091989721?check_suite_focus=true#step:7:373
```
yarn install v1.22.19
warning ../../package.json: No license field
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
warning " > ts-node@10.8.1" has unmet peer dependency "typescript@>=2.7".
[4/4] Building fresh packages...
error /home/runner/work/ecosystem-tests/ecosystem-tests/platforms-serverless/netlify-cli/node_modules/netlify-cli: Command failed.
Exit code: 7
Command: node ./scripts/postinstall.js
Arguments: 
Directory: /home/runner/work/ecosystem-tests/ecosystem-tests/platforms-serverless/netlify-cli/node_modules/netlify-cli
Output:
/home/runner/work/ecosystem-tests/ecosystem-tests/platforms-serverless/netlify-cli/node_modules/netlify-redirector/lib/redirects.js:116
      throw ex;
      ^
TypeError: (intermediate value).conflicts is not a function
    at createDevCommand (/home/runner/work/ecosystem-tests/ecosystem-tests/platforms-serverless/netlify-cli/node_modules/netlify-cli/src/commands/dev/dev.js:587:10)
    at createMainCommand (/home/runner/work/ecosystem-tests/ecosystem-tests/platforms-serverless/netlify-cli/node_modules/netlify-cli/src/commands/main.js:172:3)
    at postInstall (/home/runner/work/ecosystem-tests/ecosystem-tests/platforms-serverless/netlify-cli/node_modules/netlify-cli/scripts/postinstall.js:35:21)
    at Object.<anonymous> (/home/runner/work/ecosystem-tests/ecosystem-tests/platforms-serverless/netlify-cli/node_modules/netlify-cli/scripts/postinstall.js:56:1)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:75:12)
    at internal/main/run_main_module.js:17:47
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
+ code=7
```

Digging a bit shows that it should be the following line
https://github.com/netlify/cli/blob/85db12bc8c93fea93b8ce03be334081f09e2d317/scripts/postinstall.js#L35

Introduced in the following PR
https://github.com/netlify/cli/pull/3841

Note, our repo is public and the project folder is:
https://github.com/prisma/ecosystem-tests/tree/renovate/netlify-cli-10.x/platforms-serverless/netlify-cli

### Steps to reproduce

```sh
git clone https://github.com/prisma/ecosystem-tests.git
git checkout renovate/netlify-cli-10.x
cd /workspaces/ecosystem-tests/platforms-serverless/netlify-cli
yarn
```

### Environment

GitHub Codespaces:

  System:
    OS: Linux 5.4 Ubuntu 20.04.4 LTS (Focal Fossa)
    CPU: (2) x64 Intel(R) Xeon(R) Platinum 8272CL CPU @ 2.60GHz
    Memory: 1.04 GB / 3.84 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 16.14.2 - ~/.nodejs/current/bin/node
    Yarn: 1.22.15 - /opt/yarn/stable/bin/yarn
    npm: 8.5.0 - ~/.nodejs/current/bin/npm
  npmPackages:
    netlify-cli: 10.6.3 => 10.6.3

**Comment by Jolg42** [comment]
Note: this is the process.argv logged (shows that it doesn't include `.yarn`)
<img width="705" alt="Screen Shot 2022-06-28 at 16 27 01" src="https://user-images.githubusercontent.com/1328733/176207600-b6c027d4-b7a2-411e-a1e6-1baf16abefb6.png">

**Comment by danez** [comment]
Thanks for all the investigation and reporting it to us.

I create a PR that will fix the issue. The underlying problem is that we use functionality from `commander.js` that is not available in the version we specify in `package.json`. You can try yourself to update `commander.js` to at least 9.2.0 in your `yarn.lock` file.

**Comment by Jolg42** [comment]
@danez Thank you 💚 
I can confirm that [netlify-cli to v10.8.0](https://github.com/prisma/ecosystem-tests/pull/2864) works now
