### ISSUE TITLE
DX: Deploy Error when function modules are missing

### ISSUE THREAD

**Issue by DavidWells** [netlify/cli#475]
When a function with package.json + deps in code hasn't installed the node_modules a someone cryptic error message is thrown (see below)

Reproduce:

1. Clone https://github.com/netlify-labs/all-the-functions
2. `netlify init`
3. `npm install`
4. `netlify deploy`
5. See error

Error:

```
🏃  Hashing files... ›   Warning:
 ›   {}
 ›
🚶  Hashing netlify.tomlError: Could not find "encoding" module in file: /12-fetch-external-api/12-fetch-external-api.js.
Please ensure "encoding" is installed in the project.
    at handle (~/.nvm/versions/node/v10.4.1/lib/node_modules/netlify-cli/node_modules/@netlify/zip-it-and-ship-it/src/finders.js:76:17)
    at precinct.paperwork.forEach.dependency (~/.nvm/versions/node/v10.4.1/lib/node_modules/netlify-cli/node_modules/@netlify/zip-it-and-ship-it/src/finders.js:102:11)
    at Array.forEach (<anonymous>)
    at getDependencies (~/.nvm/versions/node/v10.4.1/lib/node_modules/netlify-cli/node_modules/@netlify/zip-it-and-ship-it/src/finders.js:95:8)
    at filesForFunctionZip (~/.nvm/versions/node/v10.4.1/lib/node_modules/netlify-cli/node_modules/@netlify/zip-it-and-ship-it/src/zip.js:57:7)
    at zipJs (~/.nvm/versions/node/v10.4.1/lib/node_modules/netlify-cli/node_modules/@netlify/zip-it-and-ship-it/src/zip.js:110:3)
    at zipFunction (~/.nvm/versions/node/v10.4.1/lib/node_modules/netlify-cli/node_modules/@netlify/zip-it-and-ship-it/src/zip.js:143:12)
    at ~/.nvm/versions/node/v10.4.1/lib/node_modules/netlify-cli/node_modules/@netlify/zip-it-and-ship-it/src/zip.js:181:9
    at element (~/.nvm/versions/node/v10.4.1/lib/node_modules/netlify-cli/node_modules/p-all/index.js:4:67)
    at Promise.resolve.then.element (~/.nvm/versions/node/v10.4.1/lib/node_modules/netlify-cli/node_modules/p-map/index.js:47:21)
```

![image](https://user-images.githubusercontent.com/532272/55254414-08fb7980-5215-11e9-9ec1-2c32d37d579a.png)

Next error:

```
⠂ Hashing asset-manifest.jsonError: Could not find "faker" module in file: /6-using-node-modules/6-using-node-modules.js.
Please ensure "faker" is installed in the project.
    at handle (~/.nvm/versions/node/v10.4.1/lib/node_modules/netlify-cli/node_modules/@netlify/zip-it-and-ship-it/src/finders.js:76:17)
    at precinct.paperwork.forEach.dependency (~/.nvm/versions/node/v10.4.1/lib/node_modules/netlify-cli/node_modules/@netlify/zip-it-and-ship-it/src/finders.js:102:11)
    at Array.forEach (<anonymous>)
    at getDependencies (~/.nvm/versions/node/v10.4.1/lib/node_modules/netlify-cli/node_modules/@netlify/zip-it-and-ship-it/src/finders.js:95:8)
    at filesForFunctionZip (~/.nvm/versions/node/v10.4.1/lib/node_modules/netlify-cli/node_modules/@netlify/zip-it-and-ship-it/src/zip.js:57:7)
    at zipJs (~/.nvm/versions/node/v10.4.1/lib/node_modules/netlify-cli/node_modules/@netlify/zip-it-and-ship-it/src/zip.js:110:3)
    at zipFunction (~/.nvm/versions/node/v10.4.1/lib/node_modules/netlify-cli/node_modules/@netlify/zip-it-and-ship-it/src/zip.js:143:12)
    at ~/.nvm/versions/node/v10.4.1/lib/node_modules/netlify-cli/node_modules/@netlify/zip-it-and-ship-it/src/zip.js:181:9
    at element (~/.nvm/versions/node/v10.4.1/lib/node_modules/netlify-cli/node_modules/p-all/index.js:4:67)
    at Promise.resolve.then.element (~/.nvm/versions/node/v10.4.1/lib/node_modules/netlify-cli/node_modules/p-map/index.js:47:21)
```

This is happening because the modules aren't resolved in the folder or up the tree

## Possible solutions

1. Make the "module not found" error nicer with a hint to "make sure you install your dependancies in that folder"
2. If `package.json` found in functions folder with `dependencies` listed AND no node_modules found, automatically install the node_modules and automatically retry the command. This should alleviate the problem unless the code deps are not listed in package.json (user error)
4. Other ? ¯\_(ツ)_/¯

**Comment by erezrokah** [comment]
Closing this as stale. I believe this was fixed in https://github.com/netlify/zip-it-and-ship-it/issues/30 and probably other improvements to `zisi`.

If this still happens please comment.
