### ISSUE TITLE
Error during invocation:  Error: only one instance of babel-polyfill is allowed

### ISSUE THREAD

**Issue by preconception** [netlify/cli#478]
**- Do you want to request a *feature* or report a *bug*?**

Bug

**- What is the current behavior?**

Subsequent unique function calls while in local environment fail with error: "Error during invocation:  Error: only one instance of babel-polyfill is allowed"

**- If the current behavior is a bug, please provide the steps to reproduce.**

AuthCheck function runs on page load. It is successful if no other function aside from itself has previously been run inside of the current netlify-dev or letlify-lambda session.

For example, a successful AuthCheck invocation followed by an UpdateUser invocation results in "Error during invocation:  Error: only one instance of babel-polyfill is allowed" alongside a 500 error. No subsequent functions calls, even the previously functioning AuthCheck can be made successfully - all resulting in: Error during invocation:  Error: only one instance of babel-polyfill is allowed.

The full log is as follows:

```
Error during invocation:  Error: only one instance of babel-polyfill is allowed
    at Object.<anonymous> (C:\Users\Sean\Documents\GitHub\app\built-lambda\user-authcheck.js:8263:9)
    at __webpack_require__ (C:\Users\Sean\Documents\GitHub\app\built-lambda\user-authcheck.js:120:30)
    at Object.<anonymous> (C:\Users\Sean\Documents\GitHub\app\built-lambda\user-authcheck.js:27530:1)
    at __webpack_require__ (C:\Users\Sean\Documents\GitHub\app\built-lambda\user-authcheck.js:120:30)
    at C:\Users\Sean\Documents\GitHub\app\built-lambda\user-authcheck.js:166:18
    at C:\Users\Sean\Documents\GitHub\app\built-lambda\user-authcheck.js:169:10
    at webpackUniversalModuleDefinition (C:\Users\Sean\Documents\GitHub\app\built-lambda\user-authcheck.js:98:20)
    at Object.../../../node_modules/truevault/build/index-node.js (C:\Users\Sean\Documents\GitHub\app\built-lambda\user-authcheck.js:100:3)       
    at __webpack_require__ (C:\Users\Sean\Documents\GitHub\app\built-lambda\user-authcheck.js:20:30)
    at Module../user-authcheck.js (C:\Users\Sean\Documents\GitHub\app\built-lambda\user-authcheck.js:27550:67)
```

**I would be happy to jump on a video call to share my screen.**

**- What is the expected behavior?**

New functions should be able to be invoked without stopping, and restarting netlify-dev or netlify-lambda.

**- Please mention your node.js, and operating system version.**

12.8.0 - Windows 10 1903 64-bit.

**Comment by preconception** [comment]
This happens in conjunction with the **truevault** npm package.

**Comment by preconception** [comment]
<img width="428" alt="Screen Shot 2019-09-09 at 4 33 32 PM" src="https://user-images.githubusercontent.com/49764795/64573333-cee3e700-d31f-11e9-9992-8e5e2d6fb3cf.png">

This fixed the issue for me.

A package I was using: truevault was the issue - using babel-polyfill 6.2.3

any other package using this now deprecated feature/behavior would probably  have this problem as well.

**Comment by preconception** [comment]
target: "node",
externals:...
