### ISSUE TITLE
Can't Link Sites 4xx on Netlify API

### ISSUE THREAD

**Issue by lassiter** [netlify/cli#482]
**- Do you want to request a *feature* or report a *bug*?**
bug
**- What is the current behavior?**
Below is a common error for most commands but first discovered trying to link.
```
FetchError: invalid json response body at https://api.netlify.com/api/v1/accounts reason: Unexpected end of JSON input
    at /usr/local/lib/node_modules/netlify-cli/node_modules/node-fetch/lib/index.js:272:32
    at async NetlifyAPI.listAccountsForUser (/usr/local/lib/node_modules/netlify-cli/node_modules/netlify/src/open-api/index.js:160:20)
    at async StatusCommand.run (/usr/local/lib/node_modules/netlify-cli/src/commands/status/index.js:27:22)
    at async StatusCommand._run (/usr/local/lib/node_modules/netlify-cli/node_modules/@oclif/command/lib/command.js:44:20)
    at async Config.runCommand (/usr/local/lib/node_modules/netlify-cli/node_modules/@oclif/config/lib/config.js:151:9)
    at async Main.run (/usr/local/lib/node_modules/netlify-cli/node_modules/@oclif/command/lib/main.js:21:9)
    at async Main._run (/usr/local/lib/node_modules/netlify-cli/node_modules/@oclif/command/lib/command.js:44:20)
```
**- If the current behavior is a bug, please provide the steps to reproduce.**
This is my history:
```
  494  npm install netlify-cli -g
  495  netlify dev
  496  netlify dev
  497  gatsby develop
  498  gatsby develop
  499  gatsby develop
  500  netlify --help
  501  netlify dev --help
  502  netlify dev -l
  503  netlify link -- had error
  504  netlify link -- had error
  505  netlify link -- had error
  506  netlify link -- had error
  507  netlify link -- had error
  508  netlify login -- not a real command
  509  netlify status -- had error
```
**- What is the expected behavior?**
I'm not sure but not expecting json errors.
**- Local Environment Information**
Paste the results of `netlify status --info` here
```
lassitergregg$ netlify status --info
 ›   Error: Unexpected argument: --info
 ›   See more help with --help
```

Is this project no longer being maintained?

**Comment by lassiter** [comment]
This is a better error:
```
Lassiters-MacBook-Air:downloads lassitergregg$ netlify status
──────────────────────┐
 Current Netlify User │
──────────────────────┘
Response {
  size: 0,
  timeout: 0,
  [Symbol(Body internals)]: {
    body: PassThrough {
      _readableState: [ReadableState],
      readable: true,
      _events: [Object: null prototype],
      _eventsCount: 2,
      _maxListeners: undefined,
      _writableState: [WritableState],
      writable: false,
      allowHalfOpen: true,
      _transformState: [Object]
    },
    disturbed: false,
    error: null
  },
  [Symbol(Response internals)]: {
    url: 'https://api.netlify.com/api/v1/accounts',
    status: 401,
    statusText: 'Unauthorized',
    headers: Headers { [Symbol(map)]: [Object: null prototype] },
    counter: 0
  }
}
```

**Comment by RaeesBhatti** [comment]
@lassiter Apologies for the delay. Is this still a problem? Can you please update to latest version of `netlify-cli@2.46.0` and try again! Let us know if the issue still persists.

**Comment by lassiter** [comment]
@RaeesBhatti I'm not sure, I used something else as a provider I think.
