### ISSUE TITLE
Possible bug when running nelify function:create

### ISSUE THREAD

**Issue by aisflat439** [netlify/cli#503]
**- Do you want to request a *feature* or report a *bug*?**

Report a *bug*

**- What is the current behavior?**

When running `nelify functions:create` and choosing FaunaDB GraphQL  and choosing new I got this output:

```
? This template has an optional setup script that runs after addon install. This can be helpful for first time users to try out templates. Run the script?
 Yes
Upload GraphQL Schema!
fs.js:646
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open '/home/aisflat439/backup/gatsby/rowing/functions/likes/schema.graphql'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.readFileSync (fs.js:551:33)
    at createFaunaGraphQL (/home/aisflat439/backup/gatsby/rowing/functions/likes/sync-schema.js:14:6)
    at Object.<anonymous> (/home/aisflat439/backup/gatsby/rowing/functions/likes/sync-schema.js:40:1)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Function.Module.runMain (module.js:694:10)
(node:24653) UnhandledPromiseRejectionWarning: Error: ◈ Error installing addon: 
    at Object.error (/home/aisflat439/.config/yarn/global/node_modules/@oclif/errors/lib/index.js:22:17)
    at FunctionsCreateCommand.error (/home/aisflat439/.config/yarn/global/node_modules/@oclif/command/lib/command.js:57:23)
    at createSiteAddon.then.catch.error (/home/aisflat439/.config/yarn/global/node_modules/netlify-cli/src/commands/functions/create.js:439:18)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
(node:24653) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:24653) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**- If the current behavior is a bug, please provide the steps to reproduce.**

- `netlify-cli/2.13.0 linux-x64 node-v8.16.1`
- plain gatsby new project
- run `netlify function:create`
- choose faunadb graphql
- select `y` for the extra output

**- What is the expected behavior?**

- it works without error

**- Local Environment Information**
Paste the results of `netlify status --info` here
I ran `netlify status --info` and that failed.
However `netlify status --verbose` ran 
```
──────────────────────┐
 Current Netlify User │
──────────────────────┘
Name: anonymized by me
Email: anonymized by me
Teams: 
  anonymized by me team: Collaborator

────────────────────┐
 Environment Info   │
────────────────────┘

  System:
    OS: Linux 5.0 Pop!_OS 19.04
    CPU: (8) x64 Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz
  Binaries:
    Node: 8.16.1 - ~/.nvm/versions/node/v8.16.1/bin/node
    Yarn: 1.17.3 - /usr/bin/yarn
    npm: 6.4.1 - ~/.nvm/versions/node/v8.16.1/bin/npm
  Browsers:
    Chrome: 76.0.3809.132
    Firefox: 68.0.2

────────────────────┐
 Netlify Site Info  │
────────────────────┘
Current site: adoring-noyce-4f88d1
Netlify TOML: /home/aisflat439/backup/gatsby/rowing/netlify.toml
Admin URL:    https://app.netlify.com/sites/adoring-noyce-4f88d1
Site URL:     https://adoring-noyce-4f88d1.netlify.com
Site Id:      48dd4392-b6dd-4053-b835-394d2f35e1a2
```

**Comment by sarahetter** [comment]
Closing as stale
