### ISSUE TITLE
netlify-cli 12.2.11 throws error in postinstall.mjs

### ISSUE THREAD

**Issue by eswat2** [netlify/cli#5312]
### Describe the bug

tried to install the latest version of netlify-cli globally this morning and it fails in postinstall...

```
[4/4] 🔨  Building fresh packages...
[4/4] ⠠ netlify-cli
[-/4] ⠠ waiting...
[-/4] ⠠ waiting...
error /Users/richardhess/.config/yarn/global/node_modules/netlify-cli: Command failed.
Exit code: 1
Command: node ./scripts/postinstall.mjs
Arguments:
Directory: /Users/richardhess/.config/yarn/global/node_modules/netlify-cli
Output:
node:internal/errors:484
    ErrorCaptureStackTrace(err);
    ^

Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'ajv-errors' imported from /Users/richardhess/.config/yarn/global/node_modules/@netlify/build/node_modules/@netlify/edge-bundler/dist/node/validation/manifest/index.js
    at new NodeError (node:internal/errors:393:5)
    at packageResolve (node:internal/modules/esm/resolve:860:9)
    at moduleResolve (node:internal/modules/esm/resolve:909:20)
    at defaultResolve (node:internal/modules/esm/resolve:1124:11)
    at nextResolve (node:internal/modules/esm/loader:163:28)
    at ESMLoader.resolve (node:internal/modules/esm/loader:841:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:424:18)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:76:40)
    at link (node:internal/modules/esm/module_job:75:36) {
  code: 'ERR_MODULE_NOT_FOUND'
}
```

### Steps to reproduce

i'm just installing the cli globally, there is not repo...

here's my package.json from .config/yarn/global

```
{
  "dependencies": {
    "@custom-elements-manifest/analyzer": "0.6.6",
    "@storybook/storybook-deployer": "2.8.16",
    "cloc": "2.10.0",
    "concurrently": "7.6.0",
    "create-astro": "1.2.3",
    "create-stencil": "3.1.1",
    "create-vite": "4.0.0",
    "cspell": "6.17.0",
    "eslint": "8.29.0",
    "foreman": "3.0.1",
    "lighthouse": "9.6.8",
    "markdownlint-cli": "0.32.2",
    "netlify-cli": "12.2.11",
    "newman": "5.3.2",
    "nodemon": "2.0.20",
    "np": "7.6.2",
    "npm-check-updates": "16.6.0",
    "pnpm": "7.18.2",
    "prettier": "2.8.1",
    "rollup": "3.7.4",
    "serve": "14.1.2",
    "sirv-cli": "2.0.2",
    "svgo": "3.0.2",
    "typescript": "4.9.4",
    "updtr": "4.0.0",
    "uuid": "9.0.0",
    "vercel": "28.8.0",
    "wait-on": "6.0.1"
  }
}
```

### Environment

➜  global git:(master) npx envinfo --system --binaries --npmPackages netlify-cli --npmGlobalPackages netlify-cli

  System:
    OS: macOS 13.1
    CPU: (8) arm64 Apple M1
    Memory: 212.09 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.12.1 - ~/.nvm/versions/node/v18.12.1/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 8.19.2 - ~/.nvm/versions/node/v18.12.1/bin/npm
  npmPackages:
    netlify-cli: 12.2.11 => 12.2.11

**Comment by danieltott** [comment]
I just got the same error fwiw.

My workaround was switching to `npm install global netlify-cli`

```sh
danielott@MacBook-Pro-2 lakewoodpack115.org % node -v
v16.18.0
danielott@MacBook-Pro-2 lakewoodpack115.org % yarn global add netlify-cli
yarn global v1.22.19
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
warning url-loader@1.1.2: Invalid bin field for "url-loader".
[3/4] 🔗  Linking dependencies...
warning "blitz > @testing-library/react@11.2.5" has unmet peer dependency "react@*".
warning "blitz > @testing-library/react@11.2.5" has unmet peer dependency "react-dom@*".
warning "blitz > @testing-library/react-hooks@4.0.1" has unmet peer dependency "react@>=16.9.0".
warning "blitz > react-test-renderer@17.0.1" has unmet peer dependency "react@17.0.1".
warning "blitz > @blitzjs/babel-preset > babel-plugin-superjson-next@0.3.0" has unmet peer dependency "next@>=9.0.0".
warning "blitz > @blitzjs/babel-preset > babel-plugin-superjson-next@0.3.0" has unmet peer dependency "superjson@1.x".
warning "blitz > @blitzjs/core > null-loader@4.0.1" has unmet peer dependency "webpack@^4.0.0 || ^5.0.0".
warning "blitz > @blitzjs/core > react-query@3.16.0" has unmet peer dependency "react@^16.8.0 || ^17.0.0".
warning "blitz > @blitzjs/generator > jscodeshift@0.11.0" has unmet peer dependency "@babel/preset-env@^7.1.6".
warning "blitz > eslint-config-blitz > @typescript-eslint/eslint-plugin@4.17.0" has unmet peer dependency "@typescript-eslint/parser@^4.0.0".
warning "blitz > eslint-config-blitz > @typescript-eslint/eslint-plugin@4.17.0" has unmet peer dependency "eslint@^5.0.0 || ^6.0.0 || ^7.0.0".
warning "blitz > eslint-config-blitz > eslint-config-next@11.1.0" has unmet peer dependency "eslint@^7.23.0".
warning "blitz > eslint-config-blitz > eslint-config-next@11.1.0" has unmet peer dependency "next@>=10.2.0".
warning "blitz > react-test-renderer > react-shallow-renderer@16.14.1" has unmet peer dependency "react@^16.0.0 || ^17.0.0".
warning "blitz > @blitzjs/core > next > @next/react-dev-overlay@11.0.1" has unmet peer dependency "react@^17.0.2".
warning "blitz > @blitzjs/core > next > @next/react-dev-overlay@11.0.1" has unmet peer dependency "react-dom@^17.0.2".
warning "blitz > @blitzjs/core > next > styled-jsx@3.3.2" has unmet peer dependency "react@15.x.x || 16.x.x || 17.x.x".
warning "blitz > @blitzjs/core > next > use-subscription@1.5.1" has unmet peer dependency "react@^16.8.0 || ^17.0.0".
warning "blitz > eslint-config-blitz > @typescript-eslint/eslint-plugin > @typescript-eslint/experimental-utils@4.17.0" has unmet peer dependency "eslint@*".
warning "blitz > eslint-config-blitz > eslint-config-next > @typescript-eslint/parser@4.29.3" has unmet peer dependency "eslint@^5.0.0 || ^6.0.0 || ^7.0.0".
warning "blitz > eslint-config-blitz > eslint-config-next > eslint-import-resolver-typescript@2.4.0" has unmet peer dependency "eslint@*".
warning "blitz > eslint-config-blitz > eslint-config-next > eslint-plugin-import@2.24.2" has unmet peer dependency "eslint@^2 || ^3 || ^4 || ^5 || ^6 || ^7.2.0".
warning "blitz > eslint-config-blitz > eslint-config-next > eslint-plugin-jsx-a11y@6.4.1" has unmet peer dependency "eslint@^3 || ^4 || ^5 || ^6 || ^7".
warning "blitz > eslint-config-blitz > eslint-config-next > eslint-plugin-react@7.24.0" has unmet peer dependency "eslint@^3 || ^4 || ^5 || ^6 || ^7".
warning "blitz > eslint-config-blitz > eslint-config-next > eslint-plugin-react-hooks@4.2.0" has unmet peer dependency "eslint@^3.0.0 || ^4.0.0 || ^5.0.0 || ^6.0.0 || ^7.0.0".
warning "gatsby-cli > gatsby-recipes > babel-eslint@10.1.0" has unmet peer dependency "eslint@>= 4.12.1".
warning "gatsby-cli > gatsby-recipes > babel-loader@8.1.0" has unmet peer dependency "webpack@>=2".
warning "gatsby-cli > gatsby-recipes > babel-plugin-remove-graphql-queries@2.8.3" has unmet peer dependency "gatsby@^2.0.0".
warning "gatsby-cli > gatsby-recipes > url-loader@1.1.2" has unmet peer dependency "webpack@^3.0.0 || ^4.0.0".
warning "netlify-cli > @netlify/build > ts-node@10.9.1" has unmet peer dependency "@types/node@*".
[4/4] 🔨  Building fresh packages...
[-/18] ⢀ waiting...
[-/18] ⢀ waiting...
[9/18] ⢀ fsevents
[-/18] ⢀ waiting...
error /Users/danielott/.config/yarn/global/node_modules/netlify-cli: Command failed.
Exit code: 1
Command: node ./scripts/postinstall.mjs
Arguments: 
Directory: /Users/danielott/.config/yarn/global/node_modules/netlify-cli
Output:
/Users/danielott/.config/yarn/global/node_modules/@netlify/build/node_modules/@netlify/zip-it-and-ship-it/dist/runtimes/go/index.js:7
const cp_file_1 = __importDefault(require("cp-file"));
                                  ^

Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/danielott/.config/yarn/global/node_modules/cp-file/index.js from /Users/danielott/.config/yarn/global/node_modules/@netlify/build/node_modules/@netlify/zip-it-and-ship-it/dist/runtimes/go/index.js not supported.
Instead change the require of /Users/danielott/.config/yarn/global/node_modules/cp-file/index.js in /Users/danielott/.config/yarn/global/node_modules/@netlify/build/node_modules/@netlify/zip-it-and-ship-it/dist/runtimes/go/index.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (/Users/danielott/.config/yarn/global/node_modules/@netlify/build/node_modules/@netlify/zip-it-and-ship-it/dist/runtimes/go/index.js:7:35)
    at Object.<anonymous> (/Users/danielott/.config/yarn/global/node_modules/@netlify/build/node_modules/@netlify/zip-it-and-ship-it/dist/runtimes/index.js:10:36)
    at Object.<anonymous> (/Users/danielott/.config/yarn/global/node_modules/@netlify/build/node_modules/@netlify/zip-it-and-ship-it/dist/main.js:6:20)
    at async Promise.all (index 0)
    at async postInstall (file:///Users/danielott/.config/yarn/global/node_modules/netlify-cli/scripts/postinstall.mjs:29:35)
    at async file:///Users/danielott/.config/yarn/global/node_modules/netlify-cli/scripts/postinstall.mjs:60:1 {
```
