### ISSUE TITLE
[dev] netlify dev error

### ISSUE THREAD

**Issue by RishabhTayal** [netlify/cli#541]
**- Do you want to request a *feature* or report a *bug*?**
bug

**- What is the current behavior?**
getting error when running `netlify dev`

**- If the current behavior is a bug, please provide the steps to reproduce.**
created a brand new project using the `deploy to netlify` button. Installed `netlify` cli using `npm install netlify-cli -g`

**- What is the expected behavior?**
run dev server

**- Error**
```
◈ Netlify Dev ◈
◈ Starting Netlify Dev with create-react-app
◈ Function builder netlify-lambda detected: Running npm script build:lambda
 ›   Warning: ◈ This is a beta feature, please give us feedback on how to improve at https://github.com/netlify/cli/
yarn run v1.17.3
$ react-scripts start
Error: Command failed with exit code 1 (EPERM): yarn run build:lambda
    at makeError (/usr/local/lib/node_modules/netlify-cli/node_modules/execa/lib/error.js:58:11)
    at handlePromise (/usr/local/lib/node_modules/netlify-cli/node_modules/execa/index.js:112:26)
```

**- Local Environment Information**
Paste the results of `netlify status --verbose` here
```
──────────────────────┐
 Current Netlify User │
──────────────────────┘
Name:  Rishabh Tayal
Teams: 
  Rishabh Tayal's team: Collaborator

────────────────────┐
 Environment Info   │
────────────────────┘

  System:
    OS: macOS 10.15
    CPU: (8) x64 Intel(R) Core(TM) i7-7920HQ CPU @ 3.10GHz
  Binaries:
    Node: 10.16.3 - /usr/local/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.11.3 - /usr/local/bin/npm
  Browsers:
    Chrome: 76.0.3809.132
    Safari: 13.0

────────────────────┐
 Netlify Site Info  │
────────────────────┘
Current site: brave-agnesi-ba6ba2
Netlify TOML: /project/netlify.toml
Admin URL:    https://app.netlify.com/sites/brave-agnesi-ba6ba2
Site URL:     https://brave-agnesi-ba6ba2.netlify.com
Site Id:      aabafbd2-136e-4492-817a-102b7ccc2658
```

**Comment by DavidWells** [comment]
Does the project have `netlify-lambda` installed as a dependency?

try 

```
npm install netlify-lambda
netlify dev
```

**Comment by DavidWells** [comment]
I see the dependency in there https://github.com/RishabhTayal/mailgun-dashboard-v2/blob/master/package.json#L29

```
npm install
```

Then

```
netlify dev
```

Let me know if you are still seeing the issue 😃

**Comment by sw-yx** [comment]
nah the issue is that he’s running it twice because of function builders and npm run all and netlify lambda fails when that happens. this is the kind of thing i worry about with function builders. however in this case we can modify netlify lambda to check if it has an instance running already.

**Comment by fireattack** [comment]
Hi, today I run into a similar problem on one of my computer. I can't run `ntl dev`.

The error is as below:

```
C:\!Others\netlify-site>ntl dev
◈ Netlify Dev ◈
◈ Starting Netlify Dev with create-react-app
◈ Function builder netlify-lambda detected: Running npm script build:lambda
 »   Warning: ◈ This is a beta feature, please give us feedback on how to improve at https://github.com/netlify/cli/
yarn run v1.22.4
$ react-scripts start
Error: Command failed with exit code 1 (Unknown system error -1): yarn run build:lambda
    at makeError (C:/Users/ikena/AppData/Roaming/npm/node_modules/netlify-cli/node_modules/execa/lib/error.js:59:11)
    at handlePromise (C:/Users/ikena/AppData/Roaming/npm/node_modules/netlify-cli/node_modules/execa/index.js:112:26)
    at async DevCommand.run (C:/Users/ikena/AppData/Roaming/npm/node_modules/netlify-cli/src/commands/dev/index.js:463:9)
    at async DevCommand._run (C:/Users/ikena/AppData/Roaming/npm/node_modules/netlify-cli/node_modules/@oclif/command/lib/command.js:43:20)
    at async Config.runCommand (C:/Users/ikena/AppData/Roaming/npm/node_modules/netlify-cli/node_modules/@oclif/config/lib/config.js:172:9)
    at async Main.run (C:/Users/ikena/AppData/Roaming/npm/node_modules/netlify-cli/node_modules/@oclif/command/lib/main.js:22:9)
    at async Main._run (C:/Users/ikena/AppData/Roaming/npm/node_modules/netlify-cli/node_modules/@oclif/command/lib/command.js:43:20)
```


After some testing, I found that it is caused by the fact I put my repo in a folder starting with "!". 

Actually, `yarn duild` will reveal this issue:

```
C:\!Others\netlify-site>yarn build
yarn run v1.22.4
$ run-p build:**
$ react-scripts build
$ netlify-lambda build src/lambda
netlify-lambda: Building functions
WebpackOptionsValidationError: Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration.context: The provided value "C:\\!Others\\netlify-site\\src\\lambda" contains exclamation mark (!) which is not allowed because it's reserved for loader syntax.
   -> The base directory (absolute path!) for resolving the `entry` option. If `output.pathinfo` is set, the included pathinfo is shortened to this directory.
 - configuration.output.path: The provided value "C:\\!Others\\netlify-site\\built-lambda" contains exclamation mark (!) which is not allowed because it's reserved for loader syntax.
```

But `ntl dev` doesn't.

After moving the repo to a different folder, everything works.

I'm not sure if it's related to OP's issue, but regardless I hope this information can help you guys improving Netlify CLI tool.

**Comment by erezrokah** [comment]
Closing this as stale.
Regardless, `netlify dev` used to hide lambda build errors. This was fixed in https://github.com/netlify/cli/pull/988

**Comment by McJoe21** [comment]
What about on Android?
