### ISSUE TITLE
Netlify-cli update to 13.0.0 fails

### ISSUE THREAD

**Issue by LeonMelis** [netlify/cli#5523]
### Describe the bug

When running `yarn global add netlify-cli` I get the following error:

```bash
yarn global v1.22.18
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
warning "netlify-cli > @netlify/build > ts-node@10.9.1" has unmet peer dependency "@types/node@*".
[4/4] Building fresh packages...
[2/2] ⠄ netlify-cli
error /usr/local/share/.config/yarn/global/node_modules/netlify-cli: Command failed.
Exit code: 1
Command: node ./scripts/postinstall.mjs
Arguments: 
Directory: /usr/local/share/.config/yarn/global/node_modules/netlify-cli
Output:
file:///usr/local/share/.config/yarn/global/node_modules/@netlify/build/node_modules/@netlify/config/lib/files.js:2
import { getProperty, setProperty, deleteProperty } from 'dot-prop';
                                   ^^^^^^^^^^^^^^
SyntaxError: Named export 'deleteProperty' not found. The requested module 'dot-prop' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'dot-prop';
const { getProperty, setProperty, deleteProperty } = pkg;

    at ModuleJob._instantiate (node:internal/modules/esm/module_job:123:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:189:5)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:526:24)
    at async postInstall (file:///usr/local/share/.config/yarn/global/node_modules/netlify-cli/scripts/postinstall.mjs:29:35)
    at async file:///usr/local/share/.config/yarn/global/node_modules/netlify-cli/scripts/postinstall.mjs:60:1
```

### Steps to reproduce

1. Run 12.1.1
2. Get warning that a new version is available
3. Run `yarn global add netlify-cli`

### Environment

```
  System:
    OS: Linux 5.15 Ubuntu 22.04.1 LTS 22.04.1 LTS (Jammy Jellyfish)
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
    Memory: 8.97 GB / 30.79 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
```

Node version 16.18.1

**Comment by danez** [comment]
I was able to reproduce this, but I think this is an issue with `yarn`.
Doing `yarn global remove netlify-cli ` and afterwards `yarn global add netlify-cli` resolved the issue.

I checked all our `package.json` files and all the dependencies on `dot-prop` seem correct.

**Comment by LeonMelis** [comment]
Uninstall/reinstall worked for me.
