### ISSUE TITLE
Ability to configure watcher. EACCES issue

### ISSUE THREAD

**Issue by Vanuan** [netlify/cli#5593]
### Describe the bug

By default, netlify watches the entire project directory. Not only this inefficient, but it also blocks start of the server is any of the files in this directory has different permissions.

I have the following in my vite config:

```
  export default defineConfig({
    server: {
      watch: {
        ignored: ["**/supabase/**"],
      },
    },
  });
```

Probably the same  watch ignore option should be added to netlify.toml, but I couldn't find any.

What's the workaround?

### Steps to reproduce

1. touch test
2. sudo chown root ./test
3. netlify dev

### Environment

  System:
    OS: Linux 5.15 Ubuntu 22.04.1 LTS 22.04.1 LTS (Jammy Jellyfish)
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Memory: 22.92 GB / 31.00 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 18.13.0 - /usr/bin/node
    Yarn: 1.21.1 - /usr/bin/yarn
    npm: 8.19.3 - /usr/bin/npm

**Comment by Vanuan** [comment]
The problem should be fixed somewhere here:

https://github.com/netlify/cli/blob/c9710cfa348a6608d558283eb1a83ab24e7d1a95/src/lib/edge-functions/registry.mjs#L389-L417

**Comment by Vanuan** [comment]
Stacktrace:

```
Error: EACCES: permission denied, watch '/home/john/projects/guess-the-movie-vite/supabase/volumes/db/data'
    at FSWatcher.<computed> (node:internal/fs/watchers:244:19)
    at Object.watch (node:fs:2315:34)
    at createFsWatchInstance (/home/john/.config/yarn/global/node_modules/chokidar/lib/nodefs-handler.js:119:15)
    at setFsWatchListener (/home/john/.config/yarn/global/node_modules/chokidar/lib/nodefs-handler.js:166:15)
    at NodeFsHandler._watchWithNodeFs (/home/john/.config/yarn/global/node_modules/chokidar/lib/nodefs-handler.js:331:14)
    at NodeFsHandler._handleDir (/home/john/.config/yarn/global/node_modules/chokidar/lib/nodefs-handler.js:567:19)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at NodeFsHandler._addToNodeFs (/home/john/.config/yarn/global/node_modules/chokidar/lib/nodefs-handler.js:617:16) {
  errno: -13,
  syscall: 'watch',
  code: 'EACCES',

```

**Comment by Vanuan** [comment]
Stacktrace:

```
Error: EACCES: permission denied, watch '[redacted]'
    at FSWatcher.<computed> (node:internal/fs/watchers:244:19)
    at Object.watch (node:fs:2315:34)
    at createFsWatchInstance (/home//.config/yarn/global/node_modules/chokidar/lib/nodefs-handler.js:119:15)
    at setFsWatchListener (/home//.config/yarn/global/node_modules/chokidar/lib/nodefs-handler.js:166:15)
    at NodeFsHandler._watchWithNodeFs (/home//.config/yarn/global/node_modules/chokidar/lib/nodefs-handler.js:331:14)
    at NodeFsHandler._handleDir (/home//.config/yarn/global/node_modules/chokidar/lib/nodefs-handler.js:567:19)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at NodeFsHandler._addToNodeFs (/home//.config/yarn/global/node_modules/chokidar/lib/nodefs-handler.js:617:16) {
  errno: -13,
  syscall: 'watch',
  code: 'EACCES',

```

**Comment by Vanuan** [comment]
The ignore path should be extendable here:

https://github.com/netlify/cli/blob/c9710cfa348a6608d558283eb1a83ab24e7d1a95/src/utils/command-helpers.mjs#L223
