### ISSUE TITLE
Netlify cli picks up package.json from test folders in node_modules packages when building

### ISSUE THREAD

**Issue by searchableguy** [netlify/cli#5809]
### Describe the bug

Netlify is picking up and complaining about a malformed package.json created for test in one of the packages we use as a dependency. 

```js
SyntaxError: Unexpected end of JSON input
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at NodeFS.readJSON (file:///Users/Work/unlock/node_modules/@netlify/build-info/lib/file-system.js:154:25)
    at async defaultIdentifyPackage (file:///Users/Work/unlock/node_modules/@netlify/build-info/lib/workspaces/get-workspace-packages.js:19:30)
    at async file:///Users/Work/unlock/node_modules/@netlify/build-info/lib/workspaces/get-workspace-packages.js:53:28
    at async Promise.all (index 1)
    at async findPackages (file:///Users/Work/unlock/node_modules/@netlify/build-info/lib/workspaces/get-workspace-packages.js:62:19)
    at async Promise.all (index 10)
    at async findPackages (file:///Users/Work/unlock/node_modules/@netlify/build-info/lib/workspaces/get-workspace-packages.js:62:19)
    at async Promise.all (index 20)
    at async findPackages (file:///Users/Work/unlock/node_modules/@netlify/build-info/lib/workspaces/get-workspace-packages.js:62:19)
Could not parse JSON file /Users/Work/unlock/packages/eslint-config/node_modules/eslint-plugin-react/node_modules/resolve/test/resolver/malformed_package_json/package.json
```

### Steps to reproduce

1. Install eslint and eslint-react-plugin in a next-js starter
2. Add the config
3. Try to build and upload site in export mode using cli
```sh
export NETLIFY_NEXT_PLUGIN_SKIP=true
export NETLIFY_SITE_ID=#site_id
yarn run netlify deploy --build -s $SITE_ID -a $AUTH_TOKEN --prod --dir="out"
```
4. You will see above in error logs. 

### Environment

 ```
  System:
    OS: macOS 13.4
    CPU: (10) arm64 Apple M1 Pro
    Memory: 24.77 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.16.0 - ~/.volta/tools/image/node/18.16.0/bin/node
    Yarn: 1.22.19 - ~/.volta/tools/image/yarn/1.22.19/bin/yarn
    npm: 9.5.1 - ~/.volta/tools/image/node/18.16.0/bin/npm
```

**Comment by serhalp** [comment]
As this issue is very stale, I'm going to close it out. Please feel free to reply or open a new issue if you're still experiencing this.

If you need additional support, please check out our support page: https://www.netlify.com/support/. Thank you!
