### ISSUE TITLE
Waiting for framework port 8080 error

### ISSUE THREAD

**Issue by gabrielbdornas** [netlify/cli#5818]
### Describe the bug

I'm following [this instructions](https://www.netlify.com/blog/2020/07/13/manage-subscriptions-and-protect-content-with-stripe/) and the `ntl dev` comand run the `Waiting for framework port 8080. This can be configured using the 'targetPort' property in the netlify.toml◈ Command failed with exit code 1: npm run dev. Shutting down Netlify Dev server` error:

```
◈ Netlify Dev ◈
◈ Injecting environment variable values for all scopes
◈ Ignored general context env var: LANG (defined in process)
◈ Ignored general context env var: LC_ALL (defined in process)
◈ Setting up local development server
◈ Starting Netlify Dev with Eleventy

> learnwithjason-demo-base@1.0.0 dev
> eleventy --serve

[11ty] Problem writing Eleventy templates: (more in DEBUG output)
[11ty] 1. Having trouble writing to "_site/index.html" from "./src/index.html" (via EleventyTemplateError)
[11ty] 2. illegal file path "undefined", file:./src/_includes/default.liquid, line:11, col:5 (via RenderError)
[11ty] 3. illegal file path "undefined" (via AssertionError)
[11ty] 
[11ty] Original error stack trace: AssertionError: illegal file path "undefined"
[11ty]     at assert (/home/gabrielbdornas/code/gabrielbdornas/stripe-subscription/node_modules/liquidjs/dist/liquid.node.cjs.js:308:15)
[11ty]     at IncludeTag.render (/home/gabrielbdornas/code/gabrielbdornas/stripe-subscription/node_modules/liquidjs/dist/liquid.node.cjs.js:3178:9)
[11ty]     at render.next (<anonymous>)
[11ty]     at toPromise (/home/gabrielbdornas/code/gabrielbdornas/stripe-subscription/node_modules/liquidjs/dist/liquid.node.cjs.js:462:32)
[11ty]     at async toPromise (/home/gabrielbdornas/code/gabrielbdornas/stripe-subscription/node_modules/liquidjs/dist/liquid.node.cjs.js:470:25)
[11ty]     at async TemplateLayout.render (/home/gabrielbdornas/code/gabrielbdornas/stripe-subscription/node_modules/@11ty/eleventy/src/TemplateLayout.js:236:25)
[11ty]     at async Template.renderPageEntry (/home/gabrielbdornas/code/gabrielbdornas/stripe-subscription/node_modules/@11ty/eleventy/src/Template.js:793:17)
[11ty]     at async /home/gabrielbdornas/code/gabrielbdornas/stripe-subscription/node_modules/@11ty/eleventy/src/Template.js:822:21
[11ty]     at async Promise.all (index 0)
[11ty]     at async Promise.all (index 1)
[11ty] Wrote 0 files in 0.06 seconds (v2.0.1)
⠧ Waiting for framework port 8080. This can be configured using the 'targetPort' property in the netlify.toml◈ Command failed with exit code 1: npm run dev. Shutting down Netlify Dev server
```

Nothing suggested in [this issue](https://github.com/netlify/cli/issues/4845) worked for me.

### Steps to reproduce

1. Run `git clone git@github.com:gabrielbdornas/stripe-subscription.git`
2. cd stripe-subscription
3. npm install
4. ntl dev

### Configuration

```
stripe-subscription git:(main) netlify --version
netlify-cli/15.6.0 linux-x64 node-v16.15.1
```

### Environment

  System:
    OS: Linux 6.2 Pop!_OS 22.04 LTS
    CPU: (12) x64 Intel(R) Core(TM) i7-10710U CPU @ 1.10GHz
    Memory: 7.20 GB / 15.31 GB
    Container: Yes
    Shell: 5.8.1 - /usr/bin/zsh
  Binaries:
    Node: 16.15.1 - ~/.nvm/versions/node/v16.15.1/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.15.1/bin/yarn
    npm: 8.11.0 - ~/.nvm/versions/node/v16.15.1/bin/npm
  npmGlobalPackages:
    netlify-cli: 15.6.0

**Comment by serhalp** [comment]
Marking this as stale as it is over a year old. Please feel free to reopen if you are still having issues.
