### ISSUE TITLE
[Android] Support for Android arm LE

### ISSUE THREAD

**Issue by musagenius345** [netlify/cli#5820]
### Describe the bug

I installed the cli using termux on my Android tablet 
`npm install netlify-cli -g` 
This gave me 
`└──╼ ❯❯❯ npm install netlify-cli -g
npm WARN deprecated source-map-url@0.4.1: See https://github.com/lydell/source-map-url#deprecated
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated
[##################] / reify:rxjs: timing reifyNode:node_modules/netlify-cli/node_modules/typescript Completed in 61089ms
> unix-dgram@2.0.6 install
> node-gyp rebuild

gyp info it worked if it ends with okming reifyNode:node_modules/netlify-cli/node_modules/typescript Completed in 61089ms
gyp info using node-gyp@9.3.0
gyp info using node@19.6.1 | android | armreifyNode:node_modules/netlify-cli/node_modules/typescript Completed in 61089ms
gyp info find Python using Python version 3.11.2 found at "/data/data/com.termux/files/usr/bin/python3"mpleted in 61089ms
gyp info spawn /data/data/com.termux/files/usr/bin/python3odules/netlify-cli/node_modules/typescript Completed in 61089ms
gyp info spawn args [
gyp info spawn args   '/data/data/com.termux/files/usr/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/data/data/com.termux/files/usr/lib/node_modules/netlify-cli/node_modules/unix-dgram/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/data/data/com.termux/files/usr/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/data/data/com.termux/files/home/.cache/node-gyp/19.6.1/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/data/data/com.termux/files/home/.cache/node-gyp/19.6.1',
gyp info spawn args   '-Dnode_gyp_dir=/data/data/com.termux/files/usr/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/data/data/com.termux/files/home/.cache/node-gyp/19.6.1/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/data/data/com.termux/files/usr/lib/node_modules/netlify-cli/node_modules/unix-dgram',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info spawn make] - reify:rxjs: timing reifyNode:node_modules/netlify-cli/node_modules/typescript Completed in 61089ms
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory '/data/data/com.termux/files/usr/lib/node_modules/netlify-cli/node_modules/unix-dgram/build'
  CXX(target) Release/obj.target/unix_dgram/src/unix_dgram.oules/netlify-cli/node_modules/typescript Completed in 61089ms
../src/unix_dgram.cc:53:13: warning: unused function 'SetNonBlock' [-Wunused-function]les/typescript Completed in 61089ms
inline void SetNonBlock(int fd) {
            ^
../src/unix_dgram.cc:65:13: warning: unused function 'SetCloExec' [-Wunused-function]
inline void SetCloExec(int fd) {
            ^
2 warnings generated.- reify:rxjs: timing reifyNode:node_modules/netlify-cli/node_modules/typescript Completed in 61089ms
  SOLINK_MODULE(target) Release/obj.target/unix_dgram.nodeodules/netlify-cli/node_modules/typescript Completed in 61089ms
  COPY Release/unix_dgram.nodexjs: timing reifyNode:node_modules/netlify-cli/node_modules/typescript Completed in 61089ms
make: Leaving directory '/data/data/com.termux/files/usr/lib/node_modules/netlify-cli/node_modules/unix-dgram/build'089ms
gyp info ok
[##################] - reify:rxjs: timing reifyNode:node_modules/netlify-cli/node_modules/typescript Completed in 61089ms
> netlify-cli@15.6.0 postinstall
> node ./scripts/postinstall.mjs

[##################] - reify:rxjs: timing reifyNode:node_modules/netlify-cli/node_modules/typescript Completed in 61089ms
Success! Netlify CLI has been installed!

Your device is now configured to use Netlify CLI to deploy and manage your Netlify sites.

Next steps:

  netlify init     Connect or create a Netlify site from current directory
  netlify deploy   Deploy the latest changes to your Netlify site

For more information on the CLI run netlify help
Or visit the docs at https://cli.netlify.com

[##################] - reify:rxjs: timing reifyNode:node_modules/netlify-cli/node_modules/typescript Completed in 61089ms
> @netlify/esbuild@0.14.39 postinstall
> node install.js

/data/data/com.termux/files/usr/lib/node_modules/netlify-cli/node_modules/@netlify/esbuild/install.js:81pleted in 61089ms
    throw new Error(`Unsupported platform: ${platformKey}`);
          ^

Error: Unsupported platform: android arm LE
    at pkgAndSubpathForCurrentPlatform (/data/data/com.termux/files/usr/lib/node_modules/netlify-cli/node_modules/@netlify/esbuild/install.js:81:11)
    at checkAndPreparePackage (/data/data/com.termux/files/usr/lib/node_modules/netlify-cli/node_modules/@netlify/esbuild/install.js:220:28)
    at Object.<anonymous> (/data/data/com.termux/files/usr/lib/node_modules/netlify-cli/node_modules/@netlify/esbuild/install.js:247:1)
    at Module._compile (node:internal/modules/cjs/loader:1275:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1329:10)
    at Module.load (node:internal/modules/cjs/loader:1133:32)
    at Module._load (node:internal/modules/cjs/loader:972:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:83:12)
    at node:internal/main/run_main_module:23:47
`

### Steps to reproduce

Run `npm install netlify-cli -g`

### Environment

System:
    OS: android
    CPU: Unknown
    Memory: 671.64 MB / 1.78 GB
  Binaries:
    Node: 19.6.1 - /data/data/com.termux/files/usr/bin/node
    Yarn: 1.22.19 - /data/data/com.termux/files/usr/bin/yarn
    npm: 9.4.0 - /data/data/com.termux/files/usr/bin/npm

**Comment by serhalp** [comment]
As this issue is very stale, I'm going to close it out. Please feel free to reply or open a new issue if you're still experiencing this.

If you need additional support, please check out our support page: https://www.netlify.com/support/. Thank you!
