### ISSUE TITLE
Error: Netlify CLI has terminated unexpectedly, when running netlify dev, Angular

### ISSUE THREAD

**Issue by anvlkv** [netlify/cli#6025]
### Describe the bug

›   Error: Netlify CLI has terminated unexpectedly
This is a problem with the Netlify CLI, not with your application.
If you recently updated the CLI, consider reverting to an older version by running:

npm install -g netlify-cli@VERSION

You can use any version from https://ntl.fyi/cli-versions.

Please report this problem at https://ntl.fyi/cli-error including the error details below.

Request from ::ffff:127.0.0.1: GET /.netlify/functions/points
Response with status 200 in 560 ms.
TypeError: res.writeHead is not a function
    at ProxyServer.<anonymous> (file:///Users/anvlkv/.npm-global/lib/node_modules/netlify-cli/src/utils/proxy.mjs:410:9)
    at ProxyServer.emit (/Users/anvlkv/.npm-global/lib/node_modules/netlify-cli/node_modules/eventemitter3/index.js:204:33)
    at Socket.onOutgoingError (/Users/anvlkv/.npm-global/lib/node_modules/netlify-cli/node_modules/http-proxy/lib/http-proxy/passes/ws-incoming.js:157:16)
    at Socket.emit (node:events:529:35)
    at Socket.emit (node:domain:489:12)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at processTicksAndRejections (node:internal/process/task_queues:82:21)

  System:
    OS: macOS 12.7
    CPU: (4) x64 Intel(R) Core(TM) i7-6567U CPU @ 3.30GHz
  Binaries:
    Node: 18.18.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.8.1 - /usr/local/bin/npm
  Browsers:
    Chrome: 116.0.5845.187
    Firefox: 117.0.1
    Safari: 16.6.1
  npmGlobalPackages:
    netlify-cli: 16.4.2

### Steps to reproduce

Not sure, I think this may be happening when saving multiple files one by one. 

The command works, but fails regularly

### Configuration

[functions]
  directory = "api"

### Environment

  System:
    OS: macOS 12.7
    CPU: (4) x64 Intel(R) Core(TM) i7-6567U CPU @ 3.30GHz
    Memory: 884.27 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.18.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.8.1 - /usr/local/bin/npm
  npmGlobalPackages:
    netlify-cli: 16.4.2

**Comment by anvlkv** [comment]
And when saving same file multiple times quickly...
