### ISSUE TITLE
deploying and linking in the same command leads to an error

### ISSUE THREAD

**Issue by sw-yx** [netlify/cli#604]
**- Do you want to request a _feature_ or report a _bug_?**
bug

**- What is the current behavior?**

start with a repo that hasn't been linked but has an existing site (e.g. if you clone an existing, deployed repo onto a new machine). `ntl deploy --prod` and search by site name:

```bash
 swyxdotio   master ●  ntl deploy --prod
This folder isn't linked to a site yet
? What would you like to do? Link this directory to an existing site

netlify link will connect this folder to a site on Netlify

? How do you want to link this folder to a site? Search by full or partial site name
? Enter the site name (or just part of it): scout
Looking for sites with names containing 'scout'...


Directory Linked

Admin url: https://app.netlify.com/sites/scout-videos-51664
Site url:  https://www.swyx.io

Site id saved to /Users/swyx/Desktop/webdev/swyxdotio/.netlify/state.json

You can now run other `netlify` cli commands in this directory
Deploy path:        /Users/swyx/Desktop/webdev/swyxdotio/__sapper__/export
Configuration path: /Users/swyx/Desktop/webdev/swyxdotio/netlify.toml
Deploying to live site URL...
✔ Finished hashing 288 files
( ●    ) CDN diffing files... ›   Warning: 
 ›   {}
 ›
(   ●  ) CDN diffing files...Error: Missing required param site_id
    at Object.values.forEach.param (~/.nvm/versions/node/v10.5.0/lib/node_modules/netlify-cli/node_modules/netlify/src/open-api/index.js:34:15)
    at Array.forEach (<anonymous>)
    at NetlifyAPI.createSiteDeploy (~/.nvm/versions/node/v10.5.0/lib/node_modules/netlify-cli/node_modules/netlify/src/open-api/index.js:28:43)
    at module.exports (~/.nvm/versions/node/v10.5.0/lib/node_modules/netlify-cli/node_modules/netlify/src/deploy/index.js:77:26)






# retry again now that there is linking...
 ✘  swyxdotio   master ●  ntl deploy --prod




Deploy path:        /Users/swyx/Desktop/webdev/swyxdotio/__sapper__/export
Configuration path: /Users/swyx/Desktop/webdev/swyxdotio/netlify.toml
Deploying to live site URL...
✔ Finished hashing 288 files
✔ CDN requesting 154 files
✔ Finished uploading 155 assets
✔ Deploy is live!

Logs:              https://app.netlify.com/sites/scout-videos-51664/deploys/5dc40a515f1f79e21368c550
Unique Deploy URL: https://5dc40a515f1f79e21368c550--scout-videos-51664.netlify.com
Live URL:          https://www.swyx.io
```

**- What is the expected behavior?**

after linking, it should just deploy properly

**- Local Environment Information**

```bash

──────────────────────┐
 Current Netlify User │
──────────────────────┘
Name:   shawn wang
Email:  shawnthe1@gmail.com
Github: sw-yx
Teams: 
  TSDX:              Owner Collaborator
  swyxteam:          Owner Collaborator Controller
  JAMstack_conf:     Owner Collaborator Controller
  AwesomeSauce:      Owner Collaborator Controller
  shawn wang's team: Owner Collaborator
  Netlify:           Owner Collaborator Controller

────────────────────┐
 Environment Info   │
────────────────────┘

  System:
    OS: macOS Sierra 10.12.6
    CPU: (4) x64 Intel(R) Core(TM) i7-4650U CPU @ 1.70GHz
  Binaries:
    Node: 10.5.0 - ~/.nvm/versions/node/v10.5.0/bin/node
    Yarn: 1.7.0 - ~/.nvm/versions/node/v10.5.0/bin/yarn
    npm: 6.12.1 - ~/.nvm/versions/node/v10.5.0/bin/npm
  Browsers:
    Chrome: 78.0.3904.87
    Firefox: 61.0
    Safari: 11.1.2

────────────────────┐
 Netlify Site Info  │
────────────────────┘
Current site: scout-videos-51664
Netlify TOML: /Users/swyx/Desktop/webdev/swyxdotio/netlify.toml
Admin URL:    https://app.netlify.com/sites/scout-videos-51664
Site URL:     https://www.swyx.io
Site Id:      a84f3ffa-3206-4630-9aad-cf8f532e0aeb

```

**Comment by RaeesBhatti** [comment]
This is no longer an issue. You can link and deploy in same command in latest version without any issue. Thanks for reporting!
