### ISSUE TITLE
netlify deploy fails when executed under cron or systemd timer

### ISSUE THREAD

**Issue by ahnj** [netlify/cli#6073]
### Describe the bug

starting in v12.0.2, cron or systemd timer task `netlify deploy --debug --prod --dir .` fails with the error below.   This issue presents itself under node 16, 18, and 20. 
```
tail -f /var/log/syslog
Oct 16 16:35:43 raspberrypi netlify[24744]: file:///home/pi/.nvm/versions/node/v18.18.2/lib/node_modules/netlify-cli/bin/run.mjs:27
Oct 16 16:35:43 raspberrypi netlify[24744]:   await program.parseAsync(argv)
Oct 16 16:35:43 raspberrypi netlify[24744]:   ^^^^^
Oct 16 16:35:43 raspberrypi netlify[24744]: SyntaxError: Unexpected reserved word
Oct 16 16:35:43 raspberrypi netlify[24744]:     at Loader.moduleStrategy (internal/modules/esm/translators.js:133:18)
Oct 16 16:35:43 raspberrypi netlify[24744]:     at async link (internal/modules/esm/module_job.js:42:21)
```

### Steps to reproduce

0. npm install -g netlify-cli@12.0.2
1. create /etc/systemd/system/netlify.service 
[Unit]
Description=deployment of rsynced wxwee html files to netlify

[Service]
Type=simple
User=pi
ExecStart=/home/pi/.nvm/versions/node/v18.18.2/bin/netlify deploy --prod --dir /home/pi/rsync_target_dir
WorkingDirectory=/home/pi/rsync_target_dir

[Install]
WantedBy=multi-user.target

2. sudo systemctl daemon-reload; sudo systemctl restart netlify.service

### Configuration

N/A

### Environment

```pi@raspberrypi:~ $ npx envinfo --system --binaries --npmPackages netlify-cli --npmGlobalPackages netlify-cli

  System:
    OS: Linux 6.1 Debian GNU/Linux 11 (bullseye) 11 (bullseye)
    CPU: (4) arm64 Cortex-A72
    Memory: 710.10 MB / 1.81 GB
    Container: Yes
    Shell: 5.1.4 - /bin/bash
  Binaries:
    Node: 18.18.2 - ~/.nvm/versions/node/v18.18.2/bin/node
    npm: 9.8.1 - ~/.nvm/versions/node/v18.18.2/bin/npm
  npmGlobalPackages:
    netlify-cli: 12.0.1

pi@raspberrypi:~ $ 
```

**Comment by serhalp** [comment]
As this issue is very stale, I'm going to close it out. Please feel free to reply or open a new issue if you're still experiencing this.

If you need additional support, please check out our support page: https://www.netlify.com/support/. Thank you!
