### ISSUE TITLE
ntl dev crashes

### ISSUE THREAD

**Issue by suethepooh** [netlify/cli#6132]
### Describe the bug

while trying to submit a form on localhost to a netlify function ntl dev crashes.

### Steps to reproduce

1. run ntl dev
2. submit form to netlify function on localhost
3. ntl dev crashes

### Configuration

here's the error:

Error: Unexpected end of form
    at Multipart._final (/Users/username/projects/bg-dev/file-xfer/node_modules/busboy/lib/types/multipart.js:588:17)
    at callFinal (node:internal/streams/writable:707:12)
    at prefinish (node:internal/streams/writable:719:7)
    at finishMaybe (node:internal/streams/writable:729:5)
    at Writable.end (node:internal/streams/writable:641:5)
    at Object.handler (/Users/username/projects/bg-dev/file-xfer/.netlify/functions/upload/upload.js:65:10)
    at executeLambdaFunc (/Users/username/.nvm/versions/node/v20.3.0/lib/node_modules/netlify-cli/node_modules/lambda-local/build/lambdalocal.js:352:51)
    at Object._executeSync (/Users/username/.nvm/versions/node/v20.3.0/lib/node_modules/netlify-cli/node_modules/lambda-local/build/lambdalocal.js:377:13)
    at /Users/username/.nvm/versions/node/v20.3.0/lib/node_modules/netlify-cli/node_modules/lambda-local/build/lambdalocal.js:96:26
    at new Promise (<anonymous>)

  System:
    OS: macOS 12.7.1
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
  Binaries:
    Node: 20.3.0 - ~/.nvm/versions/node/v20.3.0/bin/node
    npm: 9.7.1 - ~/.nvm/versions/node/v20.3.0/bin/npm
  Browsers:
    Chrome: 119.0.6045.123
    Edge: 119.0.2151.46
    Safari: 17.1
  npmGlobalPackages:
    netlify-cli: 17.1.0
                                                               
netlify.toml:

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true

[[redirects]]
    from = "/*"
    to = "/index.html"
    status = 200

### Environment

  System:
    OS: macOS 12.7.1
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
    Memory: 173.82 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 20.3.0 - ~/.nvm/versions/node/v20.3.0/bin/node
    npm: 9.7.1 - ~/.nvm/versions/node/v20.3.0/bin/npm
  npmGlobalPackages:
    netlify-cli: 17.1.0

**Comment by serhalp** [comment]
As this issue is very stale, I'm going to close it out. Please feel free to reply or open a new issue if you're still experiencing this.

If you need additional support, please check out our support page: https://www.netlify.com/support/. Thank you!
