### ISSUE TITLE
npm ERR! Failed at the netlify-cli@2.21.0 postinstall script.

### ISSUE THREAD

**Issue by The4star** [netlify/cli#614]
Trying to install the CLI on WSL and i keep getting the following error output: 

> core-js@2.6.10 postinstall /root/.nvm/versions/node/v12.9.0/lib/node_modules/netlify-cli/node_modules/babel-runtime/node_modules/core-js
> node postinstall || echo "ignore"

module.js:549
    throw err;
    ^

Error: Cannot find module '/root/.nvm/versions/node/v12.9.0/lib/node_modules/netlify-cli/node_modules/babel-runtime/node_modules/core-js/postinstall'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3
ignore

> core-js@3.4.1 postinstall /root/.nvm/versions/node/v12.9.0/lib/node_modules/netlify-cli/node_modules/core-js
> node postinstall || echo "ignore"

module.js:549
    throw err;
    ^

Error: Cannot find module '/root/.nvm/versions/node/v12.9.0/lib/node_modules/netlify-cli/node_modules/core-js/postinstall'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3
ignore

> netlify-cli@2.21.0 postinstall /root/.nvm/versions/node/v12.9.0/lib/node_modules/netlify-cli
> node ./scripts/postinstall.js

module.js:549
    throw err;
    ^

Error: Cannot find module '/root/.nvm/versions/node/v12.9.0/lib/node_modules/netlify-cli/scripts/postinstall.js'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.2 (node_modules/netlify-cli/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! netlify-cli@2.21.0 postinstall: `node ./scripts/postinstall.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the netlify-cli@2.21.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-11-17T00_33_20_391Z-debug.log

**Comment by The4star** [comment]
I have fixed this error by installing using sudo. 

i had to run the following command first: $ sudo apt-get install npm

then to install the netlify CLI i ran : $ sudo npm install netlify-cli -g
