### ISSUE TITLE
`netlify dev` command acting strangely

### ISSUE THREAD

**Issue by DavidWells** [netlify/cli#617]
When running `netlify dev` via `npm start` everything works as expected. However when running `netlify dev` alone, the process crashes.

See: https://drive.google.com/a/netlify.com/file/d/10tL31Db33DbMFHiudTcv1Gz2mzK02d8q/view?usp=drivesdk

Repro https://github.com/netlify/netlify-faunadb-example/

Running `netlify dev` alone results in this error

```
netlify dev
◈ Netlify Dev ◈
◈ Injected addon env var:  FAUNADB_ADMIN_SECRET
◈ Injected addon env var:  FAUNADB_SERVER_SECRET
◈ Injected addon env var:  FAUNADB_CLIENT_SECRET
◈ Injected build setting env var:  FAUNADB_SECRET
◈ Injected build setting env var:  lol
◈ Starting Netlify Dev with create-react-app
Waiting for localhost:3000.
◈ Lambda server is listening on 34567
{ Error: spawn react-scripts ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:229:19)
    at onErrorNT (internal/child_process.js:406:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn react-scripts',
  path: 'react-scripts',
  spawnargs: [ 'start' ] }
{ Error: spawn react-scripts ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:229:19)
    at onErrorNT (internal/child_process.js:406:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn react-scripts',
  path: 'react-scripts',
  spawnargs: [ 'start' ] }

/Users/davidwells/.nvm/versions/node/v10.4.1/lib/node_modules/netlify-cli/node_modules/netlify-redirector/lib/redirects.js:116
      throw ex;
      ^
abort({"errno":"ENOENT","code":"ENOENT","syscall":"spawn react-scripts","path":"react-scripts","spawnargs":["start"]}) at Error
    at jsStackTrace (/Users/davidwells/.nvm/versions/node/v10.4.1/lib/node_modules/netlify-cli/node_modules/netlify-redirector/lib/redirects.js:1070:13)
    at stackTrace (/Users/davidwells/.nvm/versions/node/v10.4.1/lib/node_modules/netlify-cli/node_modules/netlify-redirector/lib/redirects.js:1087:12)
    at process.abort (/Users/davidwells/.nvm/versions/node/v10.4.1/lib/node_modules/netlify-cli/node_modules/netlify-redirector/lib/redirects.js:8415:44)
    at process.emit (events.js:182:13)
    at emitPromiseRejectionWarnings (internal/process/promises.js:104:20)
    at process._tickCallback (internal/process/next_tick.js:69:34)
```

**Comment by RaeesBhatti** [comment]
It seems like `command` was set to `react-scripts` and `netlify` wasn't able to find it in your PATH. This should no longer be an issue.

**Comment by RaeesBhatti** [comment]
Thanks for reporting though
