### ISSUE TITLE
Dev build fails with error No loader is configured for ".vcf" files

### ISSUE THREAD

**Issue by kcoderhtml** [netlify/cli#6217]
### Describe the bug

In my function, I have a line that loads a .VCF file as a const, and it was building fine yesterday but now today it is failing with the error. This syntax for loading a file in a function is from following this tutorial on the netlify blog https://www.netlify.com/blog/2021/08/12/how-to-include-files-in-netlify-serverless-functions/:
```
Error: Build failed with 1 error:
netlify/functions/analytics/analytics.js:8:30: ERROR: No loader is configured for ".vcf" files: netlify/functions/analytics/output.vcf
    at failureErrorWithLog (/usr/local/lib/node_modules/netlify-cli/node_modules/@netlify/zip-it-and-ship-it/node_modules/esbuild/lib/main.js:1649:15)
    at /usr/local/lib/node_modules/netlify-cli/node_modules/@netlify/zip-it-and-ship-it/node_modules/esbuild/lib/main.js:1058:25
    at runOnEndCallbacks (/usr/local/lib/node_modules/netlify-cli/node_modules/@netlify/zip-it-and-ship-it/node_modules/esbuild/lib/main.js:1484:45)
    at buildResponseToResult (/usr/local/lib/node_modules/netlify-cli/node_modules/@netlify/zip-it-and-ship-it/node_modules/esbuild/lib/main.js:1056:7)
    at /usr/local/lib/node_modules/netlify-cli/node_modules/@netlify/zip-it-and-ship-it/node_modules/esbuild/lib/main.js:1085:16
    at responseCallbacks.<computed> (/usr/local/lib/node_modules/netlify-cli/node_modules/@netlify/zip-it-and-ship-it/node_modules/esbuild/lib/main.js:703:9)
    at handleIncomingPacket (/usr/local/lib/node_modules/netlify-cli/node_modules/@netlify/zip-it-and-ship-it/node_modules/esbuild/lib/main.js:763:9)
    at Socket.readFromStdout (/usr/local/lib/node_modules/netlify-cli/node_modules/@netlify/zip-it-and-ship-it/node_modules/esbuild/lib/main.js:679:7)
    at Socket.emit (node:events:519:28)
    at Socket.emit (node:domain:488:12)

  System:
    OS: macOS 14.1.1
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
  Binaries:
    Node: 21.2.0 - /usr/local/bin/node
    npm: 10.2.4 - /usr/local/bin/npm
  Browsers:
    Safari: 17.1
  npmGlobalPackages:
    netlify-cli: 17.7.0
``` 

### Steps to reproduce

1. clone kcoderhtml/ddg-vcf and link with Netlify via `netlify link`
2. run `netlify build`
3. run `netlify dev`

### Configuration

# example netlify.toml
[build]
  command = ""
  functions = "netlify/functions"
  publish = "dist"

[dev]
  command = ""
  functions = "netlify/functions"
  publish = "dist"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[plugins]]
package = "/plugins/config"

### Environment

System:
    OS: macOS 14.1.1
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
    Memory: 31.07 MB / 8.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 21.2.0 - /usr/local/bin/node
    npm: 10.2.4 - /usr/local/bin/npm
    pnpm: 8.6.5 - /usr/local/bin/pnpm
  npmGlobalPackages:
    netlify-cli: 17.7.0

**Comment by serhalp** [comment]
As this issue is very stale, I'm going to close it out. Please feel free to reply or open a new issue if you're still experiencing this.

If you need additional support, please check out our support page: https://www.netlify.com/support/. Thank you!
