### ISSUE TITLE
Running "netlify dev" nor "netlify build" Causing Errors During Building of Functions and Edge Functions

### ISSUE THREAD

**Issue by jeromel1978** [netlify/cli#6224]
### Describe the bug

Getting errors from function builds similar to the following
X [ERROR] Could not resolve "../../../.next/required-server-files.json"

    .netlify/functions-internal/___netlify-handler/___netlify-handler.js:18:28:
      18 │ const { config }  = require("../../../.next/required-server-files.json")
         ╵                             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

and

X [ERROR] Could not resolve "react-dom/server-rendering-stub"

    node_modules/next/dist/server/future/route-modules/app-page/vendored/ssr/entrypoints.js:44:77:
      44 │ const _serverrenderingstub = /*#__PURE__*/ _interop_require_wildcard(require("react-dom/server-rendering-stub"));
         ╵                                                                              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  The path "./server-rendering-stub" is not exported by package "react-dom":

    node_modules/react-dom/package.json:39:13:
      39 │   "exports": {
         ╵              ^

  You can mark the path "react-dom/server-rendering-stub" as external to exclude it from the bundle,
  which will remove this error and leave the unresolved path in the bundle. You can also surround
  this "require" call with a try/catch block to handle this failure at run-time instead of
  bundle-time.

X [ERROR] Could not resolve "react-dom/server.edge"

    node_modules/next/dist/server/future/route-modules/app-page/vendored/ssr/entrypoints.js:47:68:
      47 │ const _serveredge = /*#__PURE__*/ _interop_require_wildcard(require("react-dom/server.edge"));
         ╵                                                                     ~~~~~~~~~~~~~~~~~~~~~~~

  The path "./server.edge" is not exported by package "react-dom":

    node_modules/react-dom/package.json:39:13:
      39 │   "exports": {

This snowballs into more errors.

This is preventing me from local builds and running netlify dev.  I have attempted many different configurations.  The one I am including is from the last attempt.

Error: Build failed with 17 errors:
.netlify/functions-internal/___netlify-odb-handler/___netlify-odb-handler.js:18:28: ERROR: Could not resolve "../../../.next/required-server-files.json"
node_modules/next/dist/server/app-render/make-get-server-inserted-html.js:15:28: ERROR: Could not resolve "react-dom/server.edge"
node_modules/next/dist/server/app-render/react-server.node.js:32:28: ERROR: Could not resolve "react-server-dom-webpack/server.node"
node_modules/next/dist/server/app-render/static/static-renderer.js:26:73: ERROR: Could not resolve "react-dom/static.edge"
node_modules/next/dist/server/app-render/static/static-renderer.js:40:30: ERROR: Could not resolve "react-dom/server.edge"
...
    at failureErrorWithLog (C:\Users\jerom\AppData\Roaming\npm\node_modules\netlify-cli\node_modules\@netlify\zip-it-and-ship-it\node_modules\esbuild\lib\main.js:1649:15)
    at C:\Users\jerom\AppData\Roaming\npm\node_modules\netlify-cli\node_modules\@netlify\zip-it-and-ship-it\node_modules\esbuild\lib\main.js:1058:25
    at runOnEndCallbacks (C:\Users\jerom\AppData\Roaming\npm\node_modules\netlify-cli\node_modules\@netlify\zip-it-and-ship-it\node_modules\esbuild\lib\main.js:1484:45)
    at buildResponseToResult (C:\Users\jerom\AppData\Roaming\npm\node_modules\netlify-cli\node_modules\@netlify\zip-it-and-ship-it\node_modules\esbuild\lib\main.js:1056:7)
    at C:\Users\jerom\AppData\Roaming\npm\node_modules\netlify-cli\node_modules\@netlify\zip-it-and-ship-it\node_modules\esbuild\lib\main.js:1085:16
    at responseCallbacks.<computed> (C:\Users\jerom\AppData\Roaming\npm\node_modules\netlify-cli\node_modules\@netlify\zip-it-and-ship-it\node_modules\esbuild\lib\main.js:703:9)
    at handleIncomingPacket (C:\Users\jerom\AppData\Roaming\npm\node_modules\netlify-cli\node_modules\@netlify\zip-it-and-ship-it\node_modules\esbuild\lib\main.js:763:9)
    at Socket.readFromStdout (C:\Users\jerom\AppData\Roaming\npm\node_modules\netlify-cli\node_modules\@netlify\zip-it-and-ship-it\node_modules\esbuild\lib\main.js:679:7)
    at Socket.emit (node:events:514:28)
    at Socket.emit (node:domain:489:12)

  System:
    OS: Windows 10 10.0.22624
    CPU: (12) x64 AMD Ryzen 5 3600X 6-Core Processor
  Binaries:
    Node: 20.5.1 - C:\Program Files\nodejs\node.EXE
    npm: 10.2.4 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22621.1470.0), Chromium (120.0.2210.39)

### Steps to reproduce

npm update
npm update -g
netlify dev

### Configuration

# [functions]
#     external_node_modules = ["aws-sdk"]
    # node_bundler = "esbuild"
# [functions."flowpiechart"]
#     included_files = ["languages/**"]
# [functions."review"]
#     included_files = ["languages/**"]
# [functions."test"]
    # included_files = ["languages/**"]
[dev]
    targetPort = 4000
# [[plugins]]
#   package = "@netlify/plugin-nextjs"

### Environment

  System:
    OS: Windows 11 10.0.22624
    CPU: (12) x64 AMD Ryzen 5 3600X 6-Core Processor
    Memory: 12.23 GB / 31.93 GB
  Binaries:
    Node: 20.5.1 - C:\Program Files\nodejs\node.EXE
    npm: 10.2.4 - ~\AppData\Roaming\npm\npm.CMD
  npmPackages:
    netlify-cli: ^17.8.0 => 17.8.0

**Comment by serhalp** [comment]
This is quite old, so I'm going to close it. Please feel free to open a new issue if you're still having issues with the latest version of the CLI.
