### ISSUE TITLE
Can't install on NodeJS 20.6.0

### ISSUE THREAD

**Issue by jcubic** [netlify/cli#6230]
### Describe the bug

Can't install on NodeJS 20.6.0 and Fedora

### Steps to reproduce

1. npm install netlify-cli -g
got this error:

```
npm WARN deprecated source-map-url@0.4.1: See https://github.com/lydell/source-map-url#deprecated
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm ERR! code 1
npm ERR! path /home/kuba/.nvm/versions/node/v20.6.0/lib/node_modules/netlify-cli
npm ERR! command failed
npm ERR! command sh -c node ./scripts/postinstall.js
npm ERR! /home/kuba/.nvm/versions/node/v20.6.0/lib/node_modules/netlify-cli/node_modules/@babel/types/lib/index.js:65
npm ERR! Object.defineProperty(exports, "__internal__deprecationWarning", {
npm ERR!        ^
npm ERR! 
npm ERR! TypeError: Cannot redefine property: __internal__deprecationWarning
npm ERR!     at Function.defineProperty (<anonymous>)
npm ERR!     at Object.<anonymous> (/home/kuba/.nvm/versions/node/v20.6.0/lib/node_modules/netlify-cli/node_modules/@babel/types/lib/index.js:65:8)
npm ERR!     at Module._compile (node:internal/modules/cjs/loader:1241:14)
npm ERR!     at Module._extensions..js (node:internal/modules/cjs/loader:1295:10)
npm ERR!     at Module.load (node:internal/modules/cjs/loader:1091:32)
npm ERR!     at Module._load (node:internal/modules/cjs/loader:938:12)
npm ERR!     at Module.require (node:internal/modules/cjs/loader:1115:19)
npm ERR!     at require (node:internal/modules/helpers:130:18)
npm ERR!     at Object.<anonymous> (/home/kuba/.nvm/versions/node/v20.6.0/lib/node_modules/netlify-cli/node_modules/@babel/types/lib/builders/validateNode.js:8:14)
npm ERR!     at Module._compile (node:internal/modules/cjs/loader:1241:14)
npm ERR! 
npm ERR! Node.js v20.6.0
```

### Configuration

Can't install neflify-cli so I don't have any configuration yet

### Environment

```
  System:
    OS: Linux 6.5 Fedora Linux 39 (Xfce)
    CPU: (8) x64 Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
    Memory: 4.33 GB / 15.27 GB
    Container: Yes
    Shell: 5.2.21 - /bin/bash
  Binaries:
    Node: 20.6.0 - ~/.nvm/versions/node/v20.6.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v20.6.0/bin/yarn
    npm: 10.2.4 - ~/.nvm/versions/node/v20.6.0/bin/npm
```

**Comment by serhalp** [comment]
This is quite old, so I'm going to close it. Please feel free to open a new issue if you're still having issues with the latest version of the CLI.
