### ISSUE TITLE
Cannot read properties of undefined (reading 'pipe') when accessing Lambda function

### ISSUE THREAD

**Issue by shrinerp** [netlify/cli#6287]
### Describe the bug

When I access the Message Lambda, I get this error. I don't know where 'pipe' is coming from.

```◈ Function Message has returned an error: Cannot read properties of undefined (reading 'pipe')
TypeError: Cannot read properties of undefined (reading 'pipe')
    at runFunctionsProxy (file:///opt/homebrew/lib/node_modules/netlify-cli/src/lib/functions/local-proxy.js:39:25)
    at Module.invokeFunction (file:///opt/homebrew/lib/node_modules/netlify-cli/src/lib/functions/runtimes/go/index.js:43:30)
    at NetlifyFunction.invoke (file:///opt/homebrew/lib/node_modules/netlify-cli/src/lib/functions/netlify-function.js:182:47)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async handler (file:///opt/homebrew/lib/node_modules/netlify-cli/src/lib/functions/server.js:169:39)

 ›   Error: Netlify CLI has terminated unexpectedly
This is a problem with the Netlify CLI, not with your application.
If you recently updated the CLI, consider reverting to an older version by running:```

### Steps to reproduce

1. Run Neltify Dev
2. Call "Message" lambda
3. Error 

### Configuration


[dev]
  targetPort = 8080
  port = 8888
  functions = "./services/"

[functions]
  directory = "./services/"

[functions."Notifications"]
  schedule = "0 7 * * *"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  

### Environment

```  System:
    OS: macOS 14.1
    CPU: (11) arm64 Apple M3 Pro
    Memory: 203.03 MB / 18.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 21.5.0 - /opt/homebrew/bin/node
    npm: 10.2.4 - /opt/homebrew/bin/npm
  npmPackages:
    netlify-cli: ^17.11.1 => 17.11.1
  npmGlobalPackages:
    netlify-cli: 17.10.1```

**Comment by serhalp** [comment]
This is quite old, so I'm going to close it. Please feel free to open a new issue if you're still having issues with the latest version of the CLI.
