### ISSUE TITLE
netlify crashed while attempting to create a site

### ISSUE THREAD

**Issue by dmose** [netlify/cli#6307]
### Describe the bug

Trying to create a site locally that already exists in the netlify cloud so that I can use the command-line tool to link the cloud version and then do a manual deploy, netlify crashed.  There were no teams listed in the prompted where I was told to select a team, so I hit return, which then crashed.

### Steps to reproduce

1. In a github repo directory that is a local version of `https://github.com/mozilla/protolight`:
```
% netlify sites:create -n protolight
? Team: 

 ›   Error: Netlify CLI has terminated unexpectedly
This is a problem with the Netlify CLI, not with your application.
If you recently updated the CLI, consider reverting to an older version by running:

npm install -g netlify-cli@VERSION

You can use any version from https://ntl.fyi/cli-versions.

Please report this problem at https://ntl.fyi/cli-error including the error details below.

TypeError: Cannot read properties of undefined (reading 'value')
    at ListPrompt.getCurrentValue (/opt/homebrew/Cellar/netlify-cli/17.13.0/libexec/lib/node_modules/netlify-cli/node_modules/inquirer/lib/prompts/list.js:121:53)
    at MapSubscriber._next (/opt/homebrew/Cellar/netlify-cli/17.13.0/libexec/lib/node_modules/netlify-cli/node_modules/rxjs/internal/operators/map.js:49:35)
    at Subscriber.next (/opt/homebrew/Cellar/netlify-cli/17.13.0/libexec/lib/node_modules/netlify-cli/node_modules/rxjs/internal/Subscriber.js:66:18)
    at TakeSubscriber._next (/opt/homebrew/Cellar/netlify-cli/17.13.0/libexec/lib/node_modules/netlify-cli/node_modules/rxjs/internal/operators/take.js:54:30)
    at Subscriber.next (/opt/homebrew/Cellar/netlify-cli/17.13.0/libexec/lib/node_modules/netlify-cli/node_modules/rxjs/internal/Subscriber.js:66:18)
    at Interface.handler (/opt/homebrew/Cellar/netlify-cli/17.13.0/libexec/lib/node_modules/netlify-cli/node_modules/rxjs/internal/observable/fromEvent.js:22:28)
    at Interface.emit (node:events:529:35)
    at Interface.emit (node:domain:489:12)
    at [_onLine] [as _onLine] (node:internal/readline/interface:423:12)
    at [_line] [as _line] (node:internal/readline/interface:894:18)

  System:
    OS: macOS 14.2.1
    CPU: (10) arm64 Apple M1 Max
  Binaries:
    Node: 18.19.0 - ~/.nvm/versions/node/v18.19.0/bin/node
    npm: 10.3.0 - /opt/homebrew/bin/npm
  Browsers:
    Chrome: 120.0.6099.216
    Firefox: 121.0
    Safari: 17.2.1
```

### Configuration

Don't have one.

### Environment

  System:
    OS: macOS 14.2.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 2.66 GB / 64.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.19.0 - ~/.nvm/versions/node/v18.19.0/bin/node
    npm: 10.3.0 - /opt/homebrew/bin/npm

**Comment by dmose** [comment]
```
% netlify --version                 
netlify-cli/17.13.1 darwin-arm64 node-v18.19.0
```

**Comment by dmose** [comment]
To be clear, I updated to 17.13.1, tried it again, and saw the same bug.

Am Do., 11. Jan. 2024 um 14:52 Uhr schrieb Dan Mosedale <
***@***.***>:
