### ISSUE TITLE
During TypeScript conversion, seeing error: No loader is configured for “.jpeg”/”.jpg”/”.png” files

### ISSUE THREAD

**Issue by NicoleJaneway** [netlify/cli#6317]
### Describe the bug

Error: Build failed with 29 errors:
src/data/products.ts:1:17: ERROR: No loader is configured for ".jpeg" files: src/img/products/cdmp-study-plan/linkedin-sales-solutions-QgYvORVDdd8-unsplash.jpeg
src/data/products.ts:2:17: ERROR: No loader is configured for ".jpeg" files: src/img/logo_bids.jpeg
src/data/products.ts:3:19: ERROR: No loader is configured for ".jpeg" files: src/img/products/tshirt/tshirt_crop.jpeg
src/data/products.ts:4:16: ERROR: No loader is configured for ".jpeg" files: src/img/products/mug/mug15_with_laptop_crop.jpeg
src/data/products.ts:5:15: ERROR: No loader is configured for ".jpg" files: src/img/products/exam-questions/exam-taker_sq.jpg
...
    at failureErrorWithLog (/Users/nicolejanewaybills/.nvm/versions/node/v16.19.1/lib/node_modules/netlify-cli/node_modules/@netlify/zip-it-and-ship-it/node_modules/esbuild/lib/main.js:1650:15)
    at /Users/nicolejanewaybills/.nvm/versions/node/v16.19.1/lib/node_modules/netlify-cli/node_modules/@netlify/zip-it-and-ship-it/node_modules/esbuild/lib/main.js:1058:25
    at runOnEndCallbacks (/Users/nicolejanewaybills/.nvm/versions/node/v16.19.1/lib/node_modules/netlify-cli/node_modules/@netlify/zip-it-and-ship-it/node_modules/esbuild/lib/main.js:1485:45)
    at buildResponseToResult (/Users/nicolejanewaybills/.nvm/versions/node/v16.19.1/lib/node_modules/netlify-cli/node_modules/@netlify/zip-it-and-ship-it/node_modules/esbuild/lib/main.js:1056:7)
    at /Users/nicolejanewaybills/.nvm/versions/node/v16.19.1/lib/node_modules/netlify-cli/node_modules/@netlify/zip-it-and-ship-it/node_modules/esbuild/lib/main.js:1085:16
    at responseCallbacks.<computed> (/Users/nicolejanewaybills/.nvm/versions/node/v16.19.1/lib/node_modules/netlify-cli/node_modules/@netlify/zip-it-and-ship-it/node_modules/esbuild/lib/main.js:703:9)
    at handleIncomingPacket (/Users/nicolejanewaybills/.nvm/versions/node/v16.19.1/lib/node_modules/netlify-cli/node_modules/@netlify/zip-it-and-ship-it/node_modules/esbuild/lib/main.js:763:9)
    at Socket.readFromStdout (/Users/nicolejanewaybills/.nvm/versions/node/v16.19.1/lib/node_modules/netlify-cli/node_modules/@netlify/zip-it-and-ship-it/node_modules/esbuild/lib/main.js:679:7)
    at Socket.emit (node:events:513:28)
    at Socket.emit (node:domain:489:12)

  System:
    OS: macOS 14.1.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
  Binaries:
    Node: 16.19.1 - ~/.nvm/versions/node/v16.19.1/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.19.1/bin/yarn
    npm: 8.19.3 - ~/.nvm/versions/node/v16.19.1/bin/npm
  Browsers:
    Chrome: 120.0.6099.216
    Edge: 120.0.2210.133
    Safari: 17.1
  npmGlobalPackages:
    netlify-cli: 17.13.2

### Steps to reproduce

In the middle of converting to TypeScript

### Configuration

# The following redirect is intended for use with most SPAs that handle
# routing internally.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
# Define which paths this specific [[headers]] block will cover.
for = "/*"
  [headers.values]
  Access-Control-Allow-Origin = "*"
  
[build]
  functions = "functions" # netlify dev uses this directory to scaffold and serve your functions
  publish = "build"

[dev]
  command = "npm run start"
  port = 8888
  targetPort = 3000
  publish = "dist" 
  autoLaunch = true
  framework = "create-react-app"

[functions]
  directory = "functions"
  node_bundler = "esbuild"
  external_node_modules = ["@mailchimp/mailchimp_marketing", "dotenv", "sib-api-v3-sdk", "stripe"]
  included_files = ["./src/data/**"]

### Environment

System:
    OS: macOS 14.1.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Memory: 30.27 GB / 64.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 16.19.1 - ~/.nvm/versions/node/v16.19.1/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.19.1/bin/yarn
    npm: 8.19.3 - ~/.nvm/versions/node/v16.19.1/bin/npm
    pnpm: 8.1.1 - ~/.nvm/versions/node/v16.19.1/bin/pnpm
  npmPackages:
    netlify-cli: ^9.16.7 => 9.16.7 
  npmGlobalPackages:
    netlify-cli: 17.13.2

**Comment by serhalp** [comment]
This is quite old, so I'm going to close it. Please feel free to open a new issue if you're still having issues with the latest version of the CLI.
