### ISSUE TITLE
[CLI] error during authentication: Warning: GitHub error: 404 { Deprecation: [@octokit/request-error] `error.code` is deprecated, use `error.status`

### ISSUE THREAD

**Issue by swyxio** [netlify/cli#632]
**- Do you want to request a _feature_ or report a _bug_?**
bug

**- What is the current behavior?**
bad error msg when correct permissions aren't set up

**- If the current behavior is a bug, please provide the steps to reproduce.**

try to deploy a site from a GH repo that you dont have permissions to deploy

**- What is the expected behavior?**

a nice error message

**What happens instead?**

```bash
rk-community-site   master  ntl init         
? What would you like to do? +  Create & configure a new site
? Team: swyxteam
Choose a unique site name (e.g. the-great-sw-yx-site.netlify.com) or leave it blank for a random name. You can update 
the site name later.
? Site name (optional): rk-community-site-fork

Site Created

Admin URL: https://app.netlify.com/sites/rk-community-site-fork
URL:       https://rk-community-site-fork.netlify.com
Site ID:   2a6515bb-e72c-41be-88b3-7c598dde8f02

? Netlify CLI needs access to your GitHub account to configure Webhooks and Deploy Keys. What would you like to do? Au
thorize with GitHub through app.netlify.com
 ›   Warning: GitHub error: 404
{ Deprecation: [@octokit/request-error] `error.code` is deprecated, use `error.status`.
    at RequestError.get (/Users/swyx/.nvm/versions/node/v10.17.0/lib/node_modules/netlify-cli/node_modules/@octokit/request-error/dist-node/index.js:29:17)
    at InitCommand.run (/Users/swyx/.nvm/versions/node/v10.17.0/lib/node_modules/netlify-cli/src/commands/init.js:215:19)
    at process._tickCallback (internal/process/next_tick.js:68:7) name: 'Deprecation' }
 ›   Error: Does the repository react-knowledgeable/rk-community-site exist and do you have the correct permissions 
 ›   to set up deploy keys?
```

**Comment by jamesgrubb** [comment]
Having the same issue

**Comment by sw-yx** [comment]
to resolve your issue, check the permissions on your GH repo.

**Comment by sarahetter** [comment]
Closing as stale
