### ISSUE TITLE
[bug] netlify-cli@2.24.0: "--json" option failed

### ISSUE THREAD

**Issue by pli01** [netlify/cli#641]
**- Do you want to request a _feature_ or report a _bug_?**
Bug
**- What is the current behavior?**
in netlify-cli@2.24.0, --json option failed.

```
netlify deploy --dir=dist  --json
 ›   Warning: 
 ›   {
 ›      "message": "invalid json response body at https://api.netlify.com/api/v1/sites/DEBUG.netlify.com/deploys reason: Unexpected end of JSON input",
 ›      "type": "invalid-json"
 ›   }
 ›
FetchError: invalid json response body at https://api.netlify.com/api/v1/sites/DEBUG.netlify.com/deploys reason: Unexpected end of JSON input
    at /usr/local/lib/node_modules/netlify-cli/node_modules/node-fetch/lib/index.js:272:32
    at async NetlifyAPI.createSiteDeploy (/usr/local/lib/node_modules/netlify-cli/node_modules/netlify/src/open-api/index.js:160:20)
    at async module.exports (/usr/local/lib/node_modules/netlify-cli/node_modules/netlify/src/deploy/index.js:77:16)
    at async NetlifyAPI.deploy (/usr/local/lib/node_modules/netlify-cli/node_modules/netlify/src/index.js:108:12)
    at async DeployCommand.run (/usr/local/lib/node_modules/netlify-cli/src/commands/deploy.js:156:17)
    at async DeployCommand._run (/usr/local/lib/node_modules/netlify-cli/node_modules/@oclif/command/lib/command.js:44:20)
    at async Config.runCommand (/usr/local/lib/node_modules/netlify-cli/node_modules/@oclif/config/lib/config.js:151:9)
    at async Main.run (/usr/local/lib/node_modules/netlify-cli/node_modules/@oclif/command/lib/main.js:21:9)
    at async Main._run (/usr/local/lib/node_modules/netlify-cli/node_modules/@oclif/command/lib/command.js:44:20)
```

**- If the current behavior is a bug, please provide the steps to reproduce.**
netlify deploy --dir=dist  --json

**- What is the expected behavior?**

```
{
  "site_id": "2d5ccfe9-35b7-4e49-ac37-d8b46153c115",
  "deploy_id": "4dgdaee74e3ac32bef791d4c",
  "deploy_url": "https://4dgdaee74e3ac32bef791d4c--DEBUG.netlify.com",
  "logs": "https://app.netlify.com/sites/DEBUG/deploys/4dgdaee74e3ac32bef791d4c",
  "url": "https://DEBUG.netlify.com"
}
```
**- Local Environment Information**
Paste the results of `netlify status --verbose` here
```
netlify status --verbose
──────────────────────┐
 Current Netlify User │
──────────────────────┘
FetchError: invalid json response body at https://api.netlify.com/api/v1/accounts reason: Unexpected end of JSON input
    at /usr/local/lib/node_modules/netlify-cli/node_modules/node-fetch/lib/index.js:272:32
    at async NetlifyAPI.listAccountsForUser (/usr/local/lib/node_modules/netlify-cli/node_modules/netlify/src/open-api/index.js:160:20)
    at async StatusCommand.run (/usr/local/lib/node_modules/netlify-cli/src/commands/status/index.js:29:22)
    at async StatusCommand._run (/usr/local/lib/node_modules/netlify-cli/node_modules/@oclif/command/lib/command.js:44:20)
```

**Comment by DavidWells** [comment]
Hey @pli01 it looks like your CLI API token might have expired.

Can you try logging out and logging in again and run the commands to verify.

```
netlify logout

netlify login
```

Let me know if this doesn't fix the issue. Sorry for the troubles

**Comment by pli01** [comment]
Hi David,
Unfortunetly, `netlify logout/login` doesn't work because i use `NETLIFY_AUTH_TOKEN and NETLIFY_SITE_ID`

I use it in a travis job in a shell script and it works like a charm  with_netlify@2.23.0_ (see the expected behavior upper)
but if failed with _netlify@2.24.0_ in the same travis environnement (see the current behaviour upper)
Nothing else changed in the environnement.

I will investigate a little more (if you have some tracks to follow?)

Thank you for your answer

**Comment by DavidWells** [comment]
Hey @pli01 

I just noticed something in the API url from that error `https://api.netlify.com/api/v1/sites/DEBUG.netlify.com/deploys`

The site id is `DEBUG.netlify.com` where it should be your site id from `process.env.NETLIFY_SITE_ID`

Can you verify `NETLIFY_SITE_ID` is set to an id that looks like `2d5ccfe9-35b7-4e49-ac37-d8b46153c115`

**Comment by pli01** [comment]
I have tried both value (site ID or site name)  which  is supported and  works well in 2.23, but same failed result in 2.24

I test on my laptop, in a simple docker container in which i install netlify-cli 2.24 and do the same command with redirection output, and it  works well in 2.24. (with site name or site id)

I suspect something "special" in a travis shell environnement when i redirect the json output to a file , perhaps with TTY

We can close the issue if you want.

Thank you for your time and answer !

**Comment by DavidWells** [comment]
No problem @pli01 glad we got it sorted out!

Have a good one!
