### ISSUE TITLE
Continously giving error for 2 hours

### ISSUE THREAD

**Issue by ha-communitypk** [netlify/cli#6770]
### Describe the bug

 »   Error: Netlify CLI has terminated unexpectedly
This is a problem with the Netlify CLI, not with your application.
If you recently updated the CLI, consider reverting to an older version by running:

npm install -g netlify-cli@VERSION

You can use any version from https://ntl.fyi/cli-versions.

Please report this problem at https://ntl.fyi/cli-error including the error details below.

TypeError: Cannot read properties of undefined (reading 'map')
    at getNormalizedError (file:///C:/Users/hp/AppData/Roaming/npm/node_modules/netlify-cli/dist/lib/functions/synchronous.js:87:41)
    at handleSynchronousFunction (file:///C:/Users/hp/AppData/Roaming/npm/node_modules/netlify-cli/dist/lib/functions/synchronous.js:33:23)
    at handler (file:///C:/Users/hp/AppData/Roaming/npm/node_modules/netlify-cli/dist/lib/functions/server.js:203:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

  System:
    OS: Windows 11 10.0.22635
    CPU: (8) x64 Intel(R) Core(TM) i5-8350U CPU @ 1.70GHz
  Binaries:
    Node: 20.15.1 - C:\Program Files\nodejs\node.EXE
    npm: 10.7.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Chromium (127.0.2651.8)

### Steps to reproduce

on git bash run "netlify dev"
first the server connected for a while then terminated immediately

### Configuration

[build]
  functions = "netlify/functions"
  publish = "public"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/app"
  status = 200

### Environment

$ npx envinfo --system --binaries --npmPackages netlify-cli --npmGlobalPackages netlify-cli
Need to install the following packages:
envinfo@7.13.0
Ok to proceed? (y)

  System:
    OS: Windows 11 10.0.22635
    CPU: (8) x64 Intel(R) Core(TM) i5-8350U CPU @ 1.70GHz
    Memory: 1.60 GB / 7.85 GB
  Binaries:
    Node: 20.15.1 - C:\Program Files\nodejs\node.EXE
    npm: 10.7.0 - C:\Program Files\nodejs\npm.CMD

**Comment by serhalp** [comment]
This is quite old, so I'm going to close it. Please feel free to open a new issue if you're still having issues with the latest version of the CLI.
