### ISSUE TITLE
Error running netlify dev

### ISSUE THREAD

**Issue by kfoubert** [netlify/cli#6792]
### Describe the bug

The command told me to report the error.

TypeError: res.writeHead is not a function
    at ProxyServer.<anonymous> (file:///home/kfoubert/source/wsfec-website/node_modules/netlify-cli/dist/utils/proxy.js:381:13)
    at ProxyServer.emit (/home/kfoubert/source/wsfec-website/node_modules/netlify-cli/node_modules/eventemitter3/index.js:204:33)
    at ClientRequest.onOutgoingError (/home/kfoubert/source/wsfec-website/node_modules/netlify-cli/node_modules/http-proxy/lib/http-proxy/passes/ws-incoming.js:157:16)
    at ClientRequest.emit (node:events:514:28)
    at ClientRequest.emit (node:domain:489:12)
    at Socket.socketOnEnd (node:_http_client:519:9)
    at Socket.emit (node:events:526:35)
    at Socket.emit (node:domain:489:12)
    at endReadableNT (node:internal/streams/readable:1376:12)
    at processTicksAndRejections (node:internal/process/task_queues:82:21)

  System:
    OS: Linux 5.15 Ubuntu 20.04.6 LTS (Focal Fossa)
    CPU: (3) x64 Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz
  Binaries:
    Node: 20.6.1 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/bin/yarn
    npm: 10.5.2 - /usr/local/bin/npm

### Steps to reproduce

simply ran `npm run netlify dev`

### Configuration

[build]
  command = "lando npm run build"
  publish = "public"

[dev]
  command = "lando npm run develop"

### Environment

System:
    OS: Linux 5.15 Ubuntu 20.04.6 LTS (Focal Fossa)
    CPU: (3) x64 Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz
    Memory: 4.06 GB / 7.76 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 20.6.1 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/bin/yarn
    npm: 10.5.2 - /usr/local/bin/npm
    pnpm: 9.7.1 - /mnt/c/Users/kfoub/AppData/Roaming/npm/pnpm
  npmPackages:
    netlify-cli: ^17.34.1 => 17.34.1

**Comment by kfoubert** [comment]
Similar to 
https://github.com/netlify/cli/issues/6773

**Comment by kfoubert** [comment]
Not I logged out and back in again and it worked.
