### ISSUE TITLE
MaxListenersExceededWarning shows every time I call a function

### ISSUE THREAD

**Issue by michalhudecek** [netlify/cli#717]
```(node:12448) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 resize listeners added to [WriteStream]. Use emitter.setMaxListeners() to increase limit```

![image](https://user-images.githubusercontent.com/1215304/74907015-d4575a00-53b2-11ea-825e-48cca8879d87.png)

I am using netlify-cli/2.35.0 . It was showing in previous versions as well though.

**Comment by RaeesBhatti** [comment]
Hey @michalhudecek Can you fill out the following:

**- What is the current behavior?**

**- If the current behavior is a bug, please provide the steps to reproduce.**

**- What is the expected behavior?**

**- Local Environment Information**
Paste the results of `netlify status --verbose` and `netlify version` here

**Comment by mthit** [comment]
@RaeesBhatti I was able to get this error with the following setup:

```
netlify-cli/2.36.0 win32-x64 node-v12.13.1
```

I narrowed it down to having this as the only code inside netlify.toml:

```
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false
```

When I got rid of the toml file and instead used a _redirects file with this content, the error was gone:
```
/* /index.html 200
```

Also, the stack log of the error was as follows:
```
MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 keypress listeners added to [ReadStream]. Use emitter.setMaxListeners() to increase limit
    at _addListener (events.js:268:17)
    at ReadStream.addListener (events.js:284:10)
    at ReadStream.Readable.on (_stream_readable.js:868:35)
    at new Interface (readline.js:230:11)
    at Object.createInterface (readline.js:78:10)
    at handleSignalEvents (C:\Users\HP\AppData\Roaming\nvm\v12.13.1\node_modules\netlify-cli\node_modules\configorama\lib\utils\handleSignalEvents.js:18:25)
    at new Configorama (C:\Users\HP\AppData\Roaming\nvm\v12.13.1\node_modules\netlify-cli\node_modules\configorama\lib\main.js:65:7)
    at module.exports (C:\Users\HP\AppData\Roaming\nvm\v12.13.1\node_modules\netlify-cli\node_modules\configorama\lib\index.js:19:20)
    at getConfig (C:\Users\HP\AppData\Roaming\nvm\v12.13.1\node_modules\netlify-cli\node_modules\@netlify\config\src\index.js:31:10)
    at resolveConfig (C:\Users\HP\AppData\Roaming\nvm\v12.13.1\node_modules\netlify-cli\node_modules\@netlify\config\src\index.js:15:24)
(node:7072) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 SIGBREAK listeners added to [process]. Use emitter.setMaxListeners() to increase limit
MaxListenersExceededWarning
Possible EventEmitter memory leak detected. 11 SIGBREAK listeners added to [process]. Use emitter.setMaxListeners() to increase limit
MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 SIGBREAK listeners added to [process]. Use emitter.setMaxListeners() to increase limit
    at _addListener (events.js:268:17)
    at process.addListener (events.js:284:10)
    at handleSignalEvents (C:\Users\HP\AppData\Roaming\nvm\v12.13.1\node_modules\netlify-cli\node_modules\configorama\lib\utils\handleSignalEvents.js:50:11)
    at new Configorama (C:\Users\HP\AppData\Roaming\nvm\v12.13.1\node_modules\netlify-cli\node_modules\configorama\lib\main.js:65:7)
    at module.exports (C:\Users\HP\AppData\Roaming\nvm\v12.13.1\node_modules\netlify-cli\node_modules\configorama\lib\index.js:19:20)
    at getConfig (C:\Users\HP\AppData\Roaming\nvm\v12.13.1\node_modules\netlify-cli\node_modules\@netlify\config\src\index.js:31:10)
    at resolveConfig (C:\Users\HP\AppData\Roaming\nvm\v12.13.1\node_modules\netlify-cli\node_modules\@netlify\config\src\index.js:15:24)
    at async parse (C:\Users\HP\AppData\Roaming\nvm\v12.13.1\node_modules\netlify-cli\node_modules\netlify-redirect-parser\netlify-config-parser.js:12:18)
    at async parseFile (C:\Users\HP\AppData\Roaming\nvm\v12.13.1\node_modules\netlify-cli\src\utils\rules-proxy.js:11:18)
    at async parseRules (C:\Users\HP\AppData\Roaming\nvm\v12.13.1\node_modules\netlify-cli\src\utils\rules-proxy.js:31:22)
> ◈ Error while killing child process: kill ESRCH
```

And line 31 of rules-proxy.js points to reading the toml file:
```
rules.push(...(await parseFile(redirectParser.parseNetlifyConfig, fileName, file)))
```
```

**Comment by RaeesBhatti** [comment]
Thanks for providing this debug information @mthit. We've identified the cause of the problem and are working on a fix.
