### ISSUE TITLE
TypeError [ERR_INVALID_ARG_TYPE] when accessing function locally

### ISSUE THREAD

**Issue by groninge01** [netlify/cli#738]
**- Do you want to request a _feature_ or report a _bug_?** 
Report a bug

**- What is the current behavior?** 
Accessing a function (http://localhost:8888/.netlify/functions/hello) gives an error:

```
_TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received null
    at validateString (internal/validators.js:117:11)
    at Object.resolve (path.js:139:9)
    at C:\Users\groninge\AppData\Roaming\npm\node_modules\netlify-cli\src\utils\serve-functions.js:166:21
    at Layer.handle [as handle_request] (C:\Users\groninge\AppData\Roaming\npm\node_modules\netlify-cli\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\groninge\AppData\Roaming\npm\node_modules\netlify-cli\node_modules\express\lib\router\route.js:137:13)
    at next (C:\Users\groninge\AppData\Roaming\npm\node_modules\netlify-cli\node_modules\express\lib\router\route.js:131:14)
    at next (C:\Users\groninge\AppData\Roaming\npm\node_modules\netlify-cli\node_modules\express\lib\router\route.js:131:14)
    at next (C:\Users\groninge\AppData\Roaming\npm\node_modules\netlify-cli\node_modules\express\lib\router\route.js:131:14)
    at next (C:\Users\groninge\AppData\Roaming\npm\node_modules\netlify-cli\node_modules\express\lib\router\route.js:131:14)
    at next (C:\Users\groninge\AppData\Roaming\npm\node_modules\netlify-cli\node_modules\express\lib\router\route.js:131:14)_
```

**- If the current behavior is a bug, please provide the steps to reproduce.**
In an empty folder create a folder named "functions". In the folder "functions" create a hello.js file with your function for example:

```
exports.handler = async () => ({
  statusCode: 200,
  body: 'hello world!'
});
```

Add a netlify.toml file to the parent folder of the "functions" folder with the following:

```
[build]
    functions = "functions"
```

Netlify-cli is installed globally so no need to install it in the project.

Run "netlify dev", access the function and the error appears.

I found the cause is a missing "package.json" file. The "findModuleDir" function in "finders.js" is looking for this file and if it is not found it returns "null". (Is my assumption correct?)

**- What is the expected behavior?**
Run "netlify dev", access the function and get the expected response.

**- Local Environment Information**
netlify-cli/2.37.0 win32-x64 node-v12.16.1

**Comment by AronBe** [comment]
I faced the same issue - suggested solution with package.json solved it

**Comment by sarahetter** [comment]
Closing as stale. Please re-open if needed
