### ISSUE TITLE
netlify watch: Error: Missing required path variable 'site_id'

### ISSUE THREAD

**Issue by gtirloni** [netlify/cli#763]
**- Do you want to request a _feature_ or report a _bug_?**
Bug

**- What is the current behavior?**
```
$ netlify watch 
Waiting for active site deploys to complete... !
Error: Missing required path variable 'site_id'
    at getRequestParam (/usr/lib/node_modules/netlify-cli/node_modules/netlify/src/methods/url.js:45:11)
    at /usr/lib/node_modules/netlify-cli/node_modules/netlify/src/methods/url.js:33:54
    at Array.map (<anonymous>)
    at getRequestParams (/usr/lib/node_modules/netlify-cli/node_modules/netlify/src/methods/url.js:33:41)
    at addPathParams (/usr/lib/node_modules/netlify-cli/node_modules/netlify/src/methods/url.js:14:22)
    at getUrl (/usr/lib/node_modules/netlify-cli/node_modules/netlify/src/methods/url.js:8:16)
    at callMethod (/usr/lib/node_modules/netlify-cli/node_modules/netlify/src/methods/index.js:33:15)
    at NetlifyAPI.listSiteBuilds (/usr/lib/node_modules/netlify-cli/node_modules/netlify/src/methods/index.js:26:14)
    at waitForBuildToFinish (/usr/lib/node_modules/netlify-cli/src/commands/watch.js:89:30)
```

**- If the current behavior is a bug, please provide the steps to reproduce.**
```
$ netlify login
$ netlify watch
```

**- What is the expected behavior?**
Command watches for deploys.

**- Local Environment Information**
```
$ netlify version
netlify-cli/2.40.0 linux-x64 node-v13.11.0
```

**Comment by gtirloni** [comment]
I think what's happening is that the cli doesn't know which sites to watch.

If I link the project's directory with a specific website, then it works:

```
$ netlify link --id=61b52e37-f31a-4e5c-bb3a-45f42a2d0e27
Linked to gtirloni in /home/gtirloni/code/gtirloni/website/.netlify/state.json

$ netlify watch
Waiting for active site deploys to complete... done

Last build
URL:   https://gtirloni.dev
Admin: https://app.netlify.com/sites/gtirloni
Deploy time: 2.322s
```

**Comment by RaeesBhatti** [comment]
Thanks for opening this issue @gtirloni. If there's not site linked to the project, it should prompt you to link one or create a new site. This seems like a bug, we'll look into this.
