### ISSUE TITLE
netlify dev --live does not trigger a live link

### ISSUE THREAD

**Issue by jasikpark** [netlify/cli#797]
**- Do you want to request a _feature_ or report a _bug_?**
# Bug

**- What is the current behavior?**
No `live-tunnel` is spawned on macOS 10.15.3 when running `netlify dev --live` installed via `npm i -g netlify-cli`

**- If the current behavior is a bug, please provide the steps to reproduce.**
run `netlify dev --live` on macOS 10.15.3

`ps aux | grep live-tunnel` output:
```shell
calebjasik       16122   0.0  0.0  4286712    696 s001  S+    2:41PM   0:00.01 grep live-tunnel
```

**- What is the expected behavior?**
A `live-tunnel` instance is spawned, and a generated link is provided to share the live dev environment

**- Local Environment Information**

`netlify-cli/2.41.0 darwin-x64 node-v13.11.0`

**Comment by RaeesBhatti** [comment]
@jasikpark Thank you for opening this ticket. Can you please the output of `netlify dev --live` command!

**Comment by jasikpark** [comment]
Well, this isn't what happened previously, but here:

```shell
% netlify dev --live
◈ Netlify Dev ◈
◈ Starting Netlify Dev with hugo

                   | EN   
-------------------+------
  Pages            | 105  
  Paginator pages  |   0  
  Non-page files   |  28  
  Static files     |   1  
  Processed images |  90  
  Aliases          |   0  
  Sitemaps         |   1  
  Cleaned          |   0  

Built in 6140 ms
Watching for changes in /Users/calebjasik/Desktop/Github/jasik-xyz/{assets,content,layouts,static}
Watching for config changes in /Users/calebjasik/Desktop/Github/jasik-xyz/config.toml
Environment: "development"
Serving pages from memory
Running in Fast Render Mode. For full rebuilds on change: hugo server --disableFastRender
Web Server is available at //localhost:1313/ (bind address 127.0.0.1)
Press Ctrl+C to stop
.
Connected!
◈ Reloading files [ 'netlify.toml' ]
ValidationError: 'port' is required.
    at validateParameters (/usr/local/lib/node_modules/netlify-cli/node_modules/wait-port/lib/validate-parameters.js:13:20)
    at /usr/local/lib/node_modules/netlify-cli/node_modules/wait-port/lib/wait-port.js:183:9
    at new Promise (<anonymous>)
    at waitPort (/usr/local/lib/node_modules/netlify-cli/node_modules/wait-port/lib/wait-port.js:173:10)
    at DevCommand.run (/usr/local/lib/node_modules/netlify-cli/src/commands/dev/index.js:482:13)
    at async DevCommand._run (/usr/local/lib/node_modules/netlify-cli/node_modules/@oclif/command/lib/command.js:44:20)
    at async Config.runCommand (/usr/local/lib/node_modules/netlify-cli/node_modules/@oclif/config/lib/config.js:160:9)
    at async Main.run (/usr/local/lib/node_modules/netlify-cli/node_modules/@oclif/command/lib/main.js:21:9)
    at async Main._run (/usr/local/lib/node_modules/netlify-cli/node_modules/@oclif/command/lib/command.js:44:20)
```

**Comment by cvan** [comment]
same behaviour for me.

it appears the breaking change occurred in [`v2.41.0`](https://github.com/netlify/cli/releases/tag/v2.41.0):
```sh
npm i -g netlify-cli@2.41.0
```

 [`v2.40.0`](https://github.com/netlify/cli/releases/tag/v2.41.0) works:
```sh
npm i -g netlify-cli@2.40.0
```

**Comment by RaeesBhatti** [comment]
Thank you all for providing this information. It was indeed a recently introduced bug. We have a fix at https://github.com/netlify/cli/pull/839, and it will be released soon.

**Comment by jasikpark** [comment]
Glad to hear!
