### ISSUE TITLE
Handle unauthenticated dev users with grace

### ISSUE THREAD

**Issue by RaeesBhatti** [netlify/cli#815]
**- Do you want to request a _feature_ or report a _bug_?**
Feature

**- What is the current behavior?**
`netlify dev` dies miserably if you're not logged in.
```
◈ Netlify Dev ◈
{ FetchError: invalid json response body at https://api.netlify.com/api/v1/sites/761206b6-2410-4027-ab0b-10b8730b356d/service-instances reason: Unexpected end of JSON input
    at C:\Users\raeesbhatti\Projects\netlify\cli\node_modules\node-fetch\lib\index.js:272:32
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
  message: 'invalid json response body at https://api.netlify.com/api/v1/sites/761206b6-2410-4027-ab0b-10b8730b356d/service-instances reason: Unexpected end of JSON input',
  type: 'invalid-json' }
◈ Error retrieving addons data for site 761206b6-2410-4027-ab0b-10b8730b356d. Double-check your login status with 'netlify status' or contact support with details of your error.
```

**- If the current behavior is a bug, please provide the steps to reproduce.**
* `netlify logout`
* `netlify dev` in your project

**- What is the expected behavior?**
`netlify dev` runs without any errors and shows a warning for the unavailable feature because of unauthenticated status.

**- Local Environment Information**
```
────────────────────┐
 Environment Info   │
────────────────────┘

  System:
    OS: Windows 10 10.0.18363
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
  Binaries:
    Node: 8.17.0 - C:\Program Files\nodejs\node.EXE
    npm: 6.13.4 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 44.18362.387.0

netlify-cli/2.43.0 win32-x64 node-v8.17.0
```

**Comment by RaeesBhatti** [comment]
Closing in favor of https://github.com/netlify/cli/issues/174
