### ISSUE TITLE
Unsupported value provided for "framework" option in config

### ISSUE THREAD

**Issue by pawel2105** [netlify/cli#847]
**- Do you want to request a _feature_ or report a _bug_?**

Bug

**- What is the current behavior?**

Running `netlify dev` with a framework config added to `netlify.toml` results in the following error:

```
Error: Unsupported value provided for "framework" option in config
    at module.exports.serverSettings (~/.nvm/versions/node/v13.13.0/lib/node_modules/netlify-cli/src/utils/detect-server.js:59:30)
    at DevCommand.run (~/.nvm/versions/node/v13.13.0/lib/node_modules/netlify-cli/src/commands/dev/index.js:413:26)
    at async DevCommand._run (~/.nvm/versions/node/v13.13.0/lib/node_modules/netlify-cli/node_modules/@oclif/command/lib/command.js:42:20)
    at async Config.runCommand (~/.nvm/versions/node/v13.13.0/lib/node_modules/netlify-cli/node_modules/@oclif/config/lib/config.js:172:9)
    at async Main.run (~/.nvm/versions/node/v13.13.0/lib/node_modules/netlify-cli/node_modules/@oclif/command/lib/main.js:21:9)
    at async Main._run (~/.nvm/versions/node/v13.13.0/lib/node_modules/netlify-cli/node_modules/@oclif/command/lib/command.js:42:20)
```

**- If the current behavior is a bug, please provide the steps to reproduce.**

My `netlify.toml` file looks like:

```
[build]
  publish = "out"
  command = "node_modules/next/dist/bin/next build"
  environment = { NODE_ENV = "production" }

[dev]
  publish = "out"
  command = "node_modules/next/dist/bin/next build"
  environment = { NODE_ENV = "production" }
  port = 8888
  targetPort = 3000
  framework = "next.js"
```

**- What is the expected behavior?**

framework config should not be throwing an error.

**- Local Environment Information**

```
────────────────────┐
 Environment Info   │
────────────────────┘

  System:
    OS: macOS Mojave 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
  Binaries:
    Node: 13.13.0 - ~/.nvm/versions/node/v13.13.0/bin/node
    Yarn: 1.22.0 - /usr/local/bin/yarn
    npm: 6.14.4 - ~/.nvm/versions/node/v13.13.0/bin/npm
  Browsers:
    Chrome: 80.0.3987.163
    Firefox: 75.0
    Safari: 13.1
  npmGlobalPackages:
    netlify-cli: 2.47.0

netlify-cli/2.47.0 darwin-x64 node-v13.13.0
```

**Comment by pawel2105** [comment]
The workaround fix for this is to change `framework = "next.js"` to `framework = "next.js.js"`

The solution is to change line of `src/utils/detect-server.js:58` from:

`const detectorName = detectorsFiles.find(dt => `${dt}.js` === devConfig.framework)`

to

`const detectorName = detectorsFiles.find(dt => dt === devConfig.framework || `${dt}.js` === devConfig.framework)`

The reason I haven't created a PR is because adding a test to `detect-server.test.js` like this one:

```
test('serverSettings: "next.js" as "framework', async t => {
  const settings = await serverSettings({ framework: 'next.js' }, {}, () => {})
  t.is(settings.framework, 'next.js')
})
```

would require adding next as a dependency:

```
"devDependencies": {
    "next": "^9.3.5"
}
```

to `src/tests/dummy-site/package.json` which breaks a bunch of existing tests. The dependency is needed in the package.json file because the next.js detector file has:

`if (!hasRequiredDeps(['next'])) return false`
