### ISSUE TITLE
Redirects setting causes a fatal exceptions

### ISSUE THREAD

**Issue by jasikpark** [netlify/cli#919]
**- Do you want to request a _feature_ or report a _bug_?**
Bug
**- What is the current behavior?**

```sh
% netlify dev -v
◈ Netlify Dev ◈
◈ Starting Netlify Dev with hugo
Waiting for localhost:1313.
Connected!
port 1313 already in use, attempting to use an available port

   ┌─────────────────────────────────────────────────┐
   │                                                 │
   │   ◈ Server now ready on http://localhost:8888   │
   │                                                 │
   └─────────────────────────────────────────────────┘

Building sites … 
                   | EN   
-------------------+------
  Pages            |  19  
  Paginator pages  |   0  
  Non-page files   |   1  
  Static files     | 778  
  Processed images |   0  
  Aliases          |   1  
  Sitemaps         |   1  
  Cleaned          |   0  

Built in 4869 ms
Watching for changes in /Users/calebjasik/Desktop/Github/getgpower-com/{assets,content,layouts,static}
Watching for config changes in /Users/calebjasik/Desktop/Github/getgpower-com/config.toml
Environment: "development"
Serving pages from memory
Running in Fast Render Mode. For full rebuilds on change: hugo server --disableFastRender
Web Server is available at http://localhost:62924/ (bind address 127.0.0.1)
Press Ctrl+C to stop
5472600 - Exception catching is disabled, this exception cannot be caught. Compile with -s DISABLE_EXCEPTION_CATCHING=0 or DISABLE_EXCEPTION_CATCHING=2 to catch.
5472600 - Exception catching is disabled, this exception cannot be caught. Compile with -s DISABLE_EXCEPTION_CATCHING=0 or DISABLE_EXCEPTION_CATCHING=2 to catch.

/usr/local/lib/node_modules/netlify-cli/node_modules/netlify-redirector/lib/redirects.js:116
      throw ex;
      ^
abort("5472600 - Exception catching is disabled, this exception cannot be caught. Compile with -s DISABLE_EXCEPTION_CATCHING=0 or DISABLE_EXCEPTION_CATCHING=2 to catch.") at Error
    at jsStackTrace (/usr/local/lib/node_modules/netlify-cli/node_modules/netlify-redirector/lib/redirects.js:1070:13)
    at stackTrace (/usr/local/lib/node_modules/netlify-cli/node_modules/netlify-redirector/lib/redirects.js:1087:12)
    at process.abort (/usr/local/lib/node_modules/netlify-cli/node_modules/netlify-redirector/lib/redirects.js:8502:44)
    at process.emit (events.js:315:20)
    at processPromiseRejections (internal/process/promises.js:209:33)
    at processTicksAndRejections (internal/process/task_queues.js:98:32)
(Use `node --trace-uncaught ...` to show where the exception was thrown)
```

**- If the current behavior is a bug, please provide the steps to reproduce.**
```
clone git@github.com:jasikpark/getgpower-com.git
run yarn install
run netlify dev
```
**- What is the expected behavior?**
Netlify Dev uses redirect rules to let me test them before sending them live.

**- Local Environment Information**
```
────────────────────┐
 Environment Info   │
────────────────────┘

  System:
    OS: macOS 10.15.4
    CPU: (4) x64 Intel(R) Core(TM) i5-6267U CPU @ 2.90GHz
  Binaries:
    Node: 14.3.0 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.5 - /usr/local/bin/npm
  Browsers:
    Chrome: 81.0.4044.138
    Firefox: 76.0.1
    Safari: 13.1
  npmGlobalPackages:
    netlify-cli: 2.51.0

netlify-cli/2.51.0 darwin-x64 node-v14.3.0
```

**Comment by jasikpark** [comment]
Tied up in this is my confusion about what exact HTTP code I should use, but I wouldn't think that matters for this bug.

**Comment by danez** [comment]
Is this still an issue? If so can you provide some more information which redirects you are trying to configure? Or can you share a repo to be able to reproduce?

**Comment by jasikpark** [comment]
i have no clue of whether it's still an issue, no longer have that original project i encountered the bug in
