### ISSUE TITLE
netlify dev --live 

### ISSUE THREAD

**Issue by goldcoders** [netlify/cli#933]
I have this error
```
◈ Installing Live Tunnel Client
/usr/lib/node_modules/netlify-cli/node_modules/netlify-redirector/lib/redirects.js:116
      throw ex;
      ^

TypeError: Cannot read property 'objectMode' of undefined
    at Source.Writable.write (/usr/lib/node_modules/netlify-cli/node_modules/decompress-tar/node_modules/readable-stream/lib/_stream_writable.js:317:22)
    at Extract._write (/usr/lib/node_modules/netlify-cli/node_modules/decompress-tar/node_modules/tar-stream/extract.js:230:21)
    at Extract._continue (/usr/lib/node_modules/netlify-cli/node_modules/decompress-tar/node_modules/tar-stream/extract.js:213:28)
    at oncontinue (/usr/lib/node_modules/netlify-cli/node_modules/decompress-tar/node_modules/tar-stream/extract.js:68:10)
    at Extract.onheader [as _onheader] (/usr/lib/node_modules/netlify-cli/node_modules/decompress-tar/node_modules/tar-stream/extract.js:183:5)
    at Extract._write (/usr/lib/node_modules/netlify-cli/node_modules/decompress-tar/node_modules/tar-stream/extract.js:250:8)
    at doWrite (/usr/lib/node_modules/netlify-cli/node_modules/decompress-tar/node_modules/readable-stream/lib/_stream_writable.js:428:64)
    at writeOrBuffer (/usr/lib/node_modules/netlify-cli/node_modules/decompress-tar/node_modules/readable-stream/lib/_stream_writable.js:417:5)
    at Extract.Writable.write (/usr/lib/node_modules/netlify-cli/node_modules/decompress-tar/node_modules/readable-stream/lib/_stream_writable.js:334:11)
    at Gunzip.ondata (_stream_readable.js:713:22)
```
Here is my Netlify.toml file , IM developing a Hugo Theme and It would be convenient  If i can Easily Check the Live Version , but im stuck at that error. 
```
[build]
  publish = "exampleSite/public"
  functions = "lambda"
  command = "hugo -s exampleSite --gc --minify --themesDir ../.. -b $HUGO_BASEURL"

[dev]
command = "hugo server mod graph --themesDir=../.. -s exampleSite"
targetPort = 1313
framework = "#custom"
port = 3000

[build.environment]
  HUGO_VERSION = "0.69.0"
  HUGO_BASEURL = "https://hugo-theme-twal-starter.netlify.app"
  HUGO_THEME = "repo"
  HUGO_ENVIRONMENT = "production"
  HUGO_ENABLEGITINFO = "true"

[context.split1]
  command = "hugo -s exampleSite --gc --minify --themesDir ../.. -b $HUGO_BASEURL --enableGitInfo"

[context.split1.environment]
  HUGO_VERSION = "0.70.0"
  HUGO_ENV = "production"

[context.deploy-preview]
  command = "hugo -s exampleSite --gc --minify --themesDir ../.. -b $HUGO_BASEURL --buildFuture"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.70.0"

[context.branch-deploy]
  command = "hugo -s exampleSite --gc --minify --themesDir ../.. -b $DEPLOY_PRIME_URL"

[context.branch-deploy.environment]
  HUGO_VERSION = "0.70.0"

[context.next.environment]
  HUGO_ENABLEGITINFO = "true"

```

**Comment by justinwaite** [comment]
Also get this error using Gatsby

**Comment by goldcoders** [comment]
I can confirm that this error is only present when you are developing a non standard hugo site...
since I am using the theme itself as the site  , this produce this error.
but if i do use a standard Hugo site and the theme is on the theme folder i dont get it.
I think it would be useful if even in theme site we can use  --live

**Comment by goldcoders** [comment]
I dont know how i fixed this error but , i can use netlify dev --live now without any problem...

**Comment by goldcoders** [comment]
things ive change on my netlify.toml
```
// this command is certainly my fault wrong command
command = "hugo server mod graph --themesDir=../.. -s exampleSite"
// change to
command = "hugo server -s exampleSite --themesDir=../.. --disableFastRender"
```
also update my hugo version to latest 0.72.0
and added template.environment
```
[template.environment]
  HUGO_BASEURL = "add your custom domain name url with https protocol"
  PAYMONGO_EMAIL = "type here your paymongo username/email"
  PAYMONGO_PASS = "type here your paymongo password"
  SES_ACCESS_KEY = "type here your AWS SES Access Key"
  SES_SECREKT_KEY = "type here your AWS SES Secret Key"
```
but now everything i working ok

**Comment by RaeesBhatti** [comment]
Glad it worked out for you @goldcoders
